package com.thexfactor117.ascension.structures;

import java.util.Random;

import com.thexfactor117.ascension.help.LogHelper;
import com.thexfactor117.ascension.help.Reference;

import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.world.World;

/**
 * 
 * @author WILLIAM
 *
 */
public class EasyMobDungeon1 extends AbandonedStructure {
	// Variables for configuration
	public static int missingBlockChance = 1;    // 1/n chance of setting block, set not less than 1, to 1 to set all blocks
	public static int spawnHeightTolerance = 4;   // Set larger for bigger structures
	public static int spawnChance = Reference.spawnChanceEasyMobDungeon1; // chance n/100

	public EasyMobDungeon1() 
	{
		structureMissingBlockChance = missingBlockChance;
		structureSpawnHeightTolerance = spawnHeightTolerance;
		structureSpawnChance = spawnChance;
		validSpawnBlocks = getValidSpawnBlocks();
		mobsToSpawn = getMobsToSpawn();

		int i = 0;
		i = addItemsForAllChests(i);
		i = addItemsForAllDungeons(i);				
	}

	protected String[] getMobsToSpawn() {
		return new String[] { "Ghost", "Barbarian", "Valkyrie" };
	}
	
	protected Block[] getValidSpawnBlocks() 
	{
		return new Block[] { Blocks.grass, Blocks.dirt, Blocks.sand, Blocks.cobblestone };
	}

	@Override
	public boolean generate(World world, Random random, int x, int y, int z) 
	{
		// Add this line to prevent more than one being built at a time
		if (running) return false; 

		// check that each corner is one of the valid spawn blocks
		// This is better for large structures (one chunk size or larger)
		if (!isValidSpawnCorners(world, x, y, z, 10, 10)){
			return false;
		}
		// Alternate way to create a large structure in a separate thread (with base)
		return generateStructureInThread(world, random, x, y, z, x, z, 10, 10, true);		
	}

	@Override
	// Lower level, from part1 of schematic
	// 11 wide (x) x 11 length (z)
	public void generateStructure(World world, Random random, int x, int y,	int z) {
		floorLevel = y;

		LogHelper.info("Generating Easy Mob Dungeon 1, part 1 at " + x + "," + y + "," + z + "!");
//		setBlock(world, random, x + 0, y + 0, z + 0, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 1, y + 0, z + 0, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 2, y + 0, z + 0, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 3, y + 0, z + 0, Blocks.dirt, 0, 3);
//		setBlock(world, random, x + 4, y + 0, z + 0, Blocks.dirt, 0, 3);
//		setBlock(world, random, x + 5, y + 0, z + 0, Blocks.dirt, 0, 3);
//		setBlock(world, random, x + 6, y + 0, z + 0, Blocks.dirt, 0, 3);
//		setBlock(world, random, x + 7, y + 0, z + 0, Blocks.dirt, 0, 3);
//		setBlock(world, random, x + 8, y + 0, z + 0, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 9, y + 0, z + 0, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 10, y + 0, z + 0, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 0, y + 0, z + 1, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 1, y + 0, z + 1, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 2, y + 0, z + 1, Blocks.dirt, 0, 3);
		setBlock(world, random, x + 3, y + 0, z + 1, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 4, y + 0, z + 1, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 5, y + 0, z + 1, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 6, y + 0, z + 1, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 7, y + 0, z + 1, Blocks.cobblestone, 0, 3);
//		setBlock(world, random, x + 8, y + 0, z + 1, Blocks.dirt, 0, 3);
//		setBlock(world, random, x + 9, y + 0, z + 1, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 10, y + 0, z + 1, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 0, y + 0, z + 2, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 1, y + 0, z + 2, Blocks.dirt, 0, 3);
		setBlock(world, random, x + 2, y + 0, z + 2, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 3, y + 0, z + 2, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 4, y + 0, z + 2, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 5, y + 0, z + 2, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 6, y + 0, z + 2, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 7, y + 0, z + 2, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 8, y + 0, z + 2, Blocks.cobblestone, 0, 3);
//		setBlock(world, random, x + 9, y + 0, z + 2, Blocks.dirt, 0, 3);
//		setBlock(world, random, x + 10, y + 0, z + 2, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 0, y + 0, z + 3, Blocks.dirt, 0, 3);
		setBlock(world, random, x + 1, y + 0, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 2, y + 0, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 3, y + 0, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 4, y + 0, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 5, y + 0, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 6, y + 0, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 7, y + 0, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 8, y + 0, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 9, y + 0, z + 3, Blocks.cobblestone, 0, 3);
//		setBlock(world, random, x + 10, y + 0, z + 3, Blocks.dirt, 0, 3);
		setBlock(world, random, x + 0, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 1, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 2, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 3, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 4, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 5, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 6, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 7, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 8, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 9, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 10, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 0, y + 0, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 1, y + 0, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 2, y + 0, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 3, y + 0, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 4, y + 0, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 5, y + 0, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 6, y + 0, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 7, y + 0, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 8, y + 0, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 9, y + 0, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 10, y + 0, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 0, y + 0, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 1, y + 0, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 2, y + 0, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 3, y + 0, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 4, y + 0, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 5, y + 0, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 6, y + 0, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 7, y + 0, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 8, y + 0, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 9, y + 0, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 10, y + 0, z + 6, Blocks.cobblestone, 0, 3);
//		setBlock(world, random, x + 0, y + 0, z + 7, Blocks.dirt, 0, 3);
		setBlock(world, random, x + 1, y + 0, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 2, y + 0, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 3, y + 0, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 4, y + 0, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 5, y + 0, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 6, y + 0, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 7, y + 0, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 8, y + 0, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 9, y + 0, z + 7, Blocks.cobblestone, 0, 3);
//		setBlock(world, random, x + 10, y + 0, z + 7, Blocks.dirt, 0, 3);
//		setBlock(world, random, x + 0, y + 0, z + 8, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 1, y + 0, z + 8, Blocks.dirt, 0, 3);
		setBlock(world, random, x + 2, y + 0, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 3, y + 0, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 4, y + 0, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 5, y + 0, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 6, y + 0, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 7, y + 0, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 8, y + 0, z + 8, Blocks.cobblestone, 0, 3);
//		setBlock(world, random, x + 9, y + 0, z + 8, Blocks.dirt, 0, 3);
//		setBlock(world, random, x + 10, y + 0, z + 8, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 0, y + 0, z + 9, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 1, y + 0, z + 9, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 2, y + 0, z + 9, Blocks.dirt, 0, 3);
		setBlock(world, random, x + 3, y + 0, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 4, y + 0, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 5, y + 0, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 6, y + 0, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 7, y + 0, z + 9, Blocks.cobblestone, 0, 3);
//		setBlock(world, random, x + 8, y + 0, z + 9, Blocks.dirt, 0, 3);
//		setBlock(world, random, x + 9, y + 0, z + 9, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 10, y + 0, z + 9, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 0, y + 0, z + 10, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 1, y + 0, z + 10, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 2, y + 0, z + 10, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 3, y + 0, z + 10, Blocks.dirt, 0, 3);
//		setBlock(world, random, x + 4, y + 0, z + 10, Blocks.dirt, 0, 3);
//		setBlock(world, random, x + 5, y + 0, z + 10, Blocks.dirt, 0, 3);
//		setBlock(world, random, x + 6, y + 0, z + 10, Blocks.dirt, 0, 3);
//		setBlock(world, random, x + 7, y + 0, z + 10, Blocks.dirt, 0, 3);
//		setBlock(world, random, x + 8, y + 0, z + 10, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 9, y + 0, z + 10, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 10, y + 0, z + 10, Blocks.grass, 0, 3);
//		setBlock(world, random, x + 0, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, random, x + 1, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, random, x + 2, y + 1, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 0, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 0, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 5, y + 1, z + 0, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 6, y + 1, z + 0, Blocks.stone, 0, 3);
		setBlock(world, random, x + 7, y + 1, z + 0, Blocks.stone, 0, 3);
//		setBlock(world, random, x + 8, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, random, x + 9, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, random, x + 10, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, random, x + 0, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, random, x + 1, y + 1, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 1, z + 1, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 1, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 1, Blocks.stonebrick, 0, 3);
//		setBlock(world, random, x + 5, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, random, x + 6, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, random, x + 7, y + 1, z + 1, Blocks.chest, 3, 3);
		setBlock(world, random, x + 8, y + 1, z + 1, Blocks.cobblestone, 0, 3);
//		setBlock(world, random, x + 9, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, random, x + 10, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, random, x + 0, y + 1, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 1, z + 2, Blocks.cobblestone, 0, 3);
//		setBlock(world, random, x + 2, y + 1, z + 2, Blocks.mob_spawner, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 2, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 2, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 5, y + 1, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 1, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 1, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 1, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 1, z + 2, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 10, y + 1, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 1, z + 3, Blocks.stone, 0, 3);
		setBlock(world, random, x + 1, y + 1, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 2, y + 1, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 3, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 1, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 1, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 1, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 1, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 1, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 1, z + 3, Blocks.stone, 0, 3);
		setBlock(world, random, x + 0, y + 1, z + 4, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 1, y + 1, z + 4, Blocks.stone, 0, 3);
		setBlock(world, random, x + 2, y + 1, z + 4, Blocks.stone, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 1, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 1, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 1, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 1, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 1, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 1, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 1, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 1, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 1, z + 7, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 0, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 1, z + 8, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 2, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 1, z + 8, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 10, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 1, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 1, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 1, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 1, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 1, z + 9, Blocks.air, 0, 3);
//		setBlock(world, random, x + 7, y + 1, z + 9, Blocks.mob_spawner, 0, 3);
		setBlock(world, random, x + 8, y + 1, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 9, y + 1, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 1, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 10, Blocks.stone, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 10, Blocks.stone, 0, 3);
		setBlock(world, random, x + 5, y + 1, z + 10, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 6, y + 1, z + 10, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 7, y + 1, z + 10, Blocks.stonebrick, 0, 3);
//		setBlock(world, random, x + 8, y + 1, z + 10, Blocks.air, 0, 3);
//		setBlock(world, random, x + 9, y + 1, z + 10, Blocks.air, 0, 3);
//		setBlock(world, random, x + 10, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 2, z + 0, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 4, y + 2, z + 0, Blocks.stone, 0, 3);

		preventLag();

		setBlock(world, random, x + 5, y + 2, z + 0, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 6, y + 2, z + 0, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 7, y + 2, z + 0, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 8, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 2, z + 1, Blocks.stone, 0, 3);
		setBlock(world, random, x + 3, y + 2, z + 1, Blocks.stone, 0, 3);
		setBlock(world, random, x + 4, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 2, z + 1, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 9, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 2, z + 2, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 2, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 2, z + 2, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 4, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 2, z + 2, Blocks.stone, 0, 3);
		setBlock(world, random, x + 10, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 2, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 1, y + 2, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 2, y + 2, z + 3, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 3, y + 2, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 2, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 2, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 2, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 2, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 2, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 2, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 2, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 0, y + 2, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 2, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 2, y + 2, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 2, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 2, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 2, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 2, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 2, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 2, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 2, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 2, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 2, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 2, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 2, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 2, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 2, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 2, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 2, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 2, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 2, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 2, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 2, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 2, z + 7, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 1, y + 2, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 2, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 2, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 2, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 2, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 2, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 2, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 2, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 2, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 2, z + 7, Blocks.stone, 0, 3);
		setBlock(world, random, x + 0, y + 2, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 2, z + 8, Blocks.stone, 0, 3);
		setBlock(world, random, x + 2, y + 2, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 2, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 2, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 2, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 2, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 2, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 2, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 2, z + 8, Blocks.stone, 0, 3);
		setBlock(world, random, x + 10, y + 2, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 2, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 2, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 2, z + 9, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 3, y + 2, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 2, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 2, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 2, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 2, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 2, z + 9, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 9, y + 2, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 2, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 2, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 2, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 2, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 2, z + 10, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 4, y + 2, z + 10, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 5, y + 2, z + 10, Blocks.stone, 0, 3);
		setBlock(world, random, x + 6, y + 2, z + 10, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 7, y + 2, z + 10, Blocks.stone, 0, 3);
		setBlock(world, random, x + 8, y + 2, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 2, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 2, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 3, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 3, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 3, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 3, z + 0, Blocks.stone, 0, 3);
		setBlock(world, random, x + 4, y + 3, z + 0, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 5, y + 3, z + 0, Blocks.stone, 0, 3);
		setBlock(world, random, x + 6, y + 3, z + 0, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 7, y + 3, z + 0, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 8, y + 3, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 3, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 3, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 3, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 3, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 3, z + 1, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 3, y + 3, z + 1, Blocks.stone, 0, 3);
		setBlock(world, random, x + 4, y + 3, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 3, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 3, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 3, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 3, z + 1, Blocks.stone, 0, 3);
		setBlock(world, random, x + 9, y + 3, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 3, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 3, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 3, z + 2, Blocks.stone, 0, 3);
		setBlock(world, random, x + 2, y + 3, z + 2, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 3, y + 3, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 3, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 3, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 3, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 3, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 3, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 3, z + 2, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 10, y + 3, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 3, z + 3, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 1, y + 3, z + 3, Blocks.stone, 0, 3);
		setBlock(world, random, x + 2, y + 3, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 3, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 3, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 3, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 3, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 3, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 3, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 3, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 3, z + 3, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 0, y + 3, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 3, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 3, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 3, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 3, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 3, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 3, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 3, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 3, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 3, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 3, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 3, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 3, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 3, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 3, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 3, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 3, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 3, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 3, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 3, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 3, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 3, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 3, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 3, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 3, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 3, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 3, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 3, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 3, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 3, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 3, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 3, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 3, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 3, z + 7, Blocks.stone, 0, 3);
		setBlock(world, random, x + 1, y + 3, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 3, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 3, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 3, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 3, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 3, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 3, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 3, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 3, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 3, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 0, y + 3, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 3, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 2, y + 3, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 3, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 3, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 3, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 3, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 3, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 3, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 3, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 10, y + 3, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 3, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 3, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 3, z + 9, Blocks.stone, 0, 3);
		setBlock(world, random, x + 3, y + 3, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 3, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 3, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 3, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 3, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 3, z + 9, Blocks.stone, 0, 3);
		setBlock(world, random, x + 9, y + 3, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 3, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 3, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 3, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 3, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 3, z + 10, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 4, y + 3, z + 10, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 5, y + 3, z + 10, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 6, y + 3, z + 10, Blocks.stone, 0, 3);
		setBlock(world, random, x + 7, y + 3, z + 10, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 8, y + 3, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 3, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 3, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 4, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 4, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 4, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 4, z + 0, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 4, y + 4, z + 0, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 5, y + 4, z + 0, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 6, y + 4, z + 0, Blocks.stone, 0, 3);
		setBlock(world, random, x + 7, y + 4, z + 0, Blocks.stone, 0, 3);
		setBlock(world, random, x + 8, y + 4, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 4, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 4, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 4, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 4, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 4, z + 1, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 3, y + 4, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 4, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 4, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 4, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 4, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 4, z + 1, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 9, y + 4, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 4, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 4, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 4, z + 2, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 2, y + 4, z + 2, Blocks.stone, 0, 3);
		setBlock(world, random, x + 3, y + 4, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 4, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 4, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 4, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 4, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 4, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 4, z + 2, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 10, y + 4, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 4, z + 3, Blocks.stone, 0, 3);
		setBlock(world, random, x + 1, y + 4, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 2, y + 4, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 4, z + 3, Blocks.air, 0, 3);

		preventLag();
		
		setBlock(world, random, x + 4, y + 4, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 4, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 4, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 4, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 4, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 4, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 4, z + 3, Blocks.stone, 0, 3);
		setBlock(world, random, x + 0, y + 4, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 1, y + 4, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 4, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 4, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 4, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 4, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 4, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 4, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 4, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 4, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 4, z + 4, Blocks.stone, 0, 3);
		setBlock(world, random, x + 0, y + 4, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 4, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 4, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 4, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 4, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 4, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 4, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 4, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 4, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 4, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 4, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 4, z + 6, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 1, y + 4, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 4, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 4, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 4, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 4, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 4, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 4, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 4, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 4, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 4, z + 6, Blocks.stone, 0, 3);
		setBlock(world, random, x + 0, y + 4, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 1, y + 4, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 4, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 4, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 4, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 4, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 4, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 4, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 4, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 4, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 4, z + 7, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 0, y + 4, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 4, z + 8, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 2, y + 4, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 4, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 4, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 4, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 4, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 4, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 4, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 4, z + 8, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 10, y + 4, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 4, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 4, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 4, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 3, y + 4, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 4, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 4, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 4, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 4, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 4, z + 9, Blocks.stone, 0, 3);
		setBlock(world, random, x + 9, y + 4, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 4, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 4, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 4, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 4, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 4, z + 10, Blocks.stone, 0, 3);
		setBlock(world, random, x + 4, y + 4, z + 10, Blocks.stone, 0, 3);
		setBlock(world, random, x + 5, y + 4, z + 10, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 6, y + 4, z + 10, Blocks.stone, 0, 3);
		setBlock(world, random, x + 7, y + 4, z + 10, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 8, y + 4, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 4, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 4, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 5, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 5, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 5, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 5, z + 0, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 4, y + 5, z + 0, Blocks.stone, 0, 3);
		setBlock(world, random, x + 5, y + 5, z + 0, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 6, y + 5, z + 0, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 7, y + 5, z + 0, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 8, y + 5, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 5, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 5, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 5, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 5, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 5, z + 1, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 3, y + 5, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 5, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 5, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 5, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 5, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 5, z + 1, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 9, y + 5, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 5, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 5, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 5, z + 2, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 2, y + 5, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 5, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 5, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 5, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 5, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 5, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 5, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 5, z + 2, Blocks.stone, 0, 3);
		setBlock(world, random, x + 10, y + 5, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 5, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 1, y + 5, z + 3, Blocks.stone, 0, 3);
		setBlock(world, random, x + 2, y + 5, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 5, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 5, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 5, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 5, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 5, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 5, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 5, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 5, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 0, y + 5, z + 4, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 1, y + 5, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 5, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 5, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 5, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 5, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 5, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 5, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 5, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 5, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 5, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 0, y + 5, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 1, y + 5, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 5, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 5, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 5, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 5, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 5, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 5, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 5, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 5, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 5, z + 5, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 0, y + 5, z + 6, Blocks.stone, 0, 3);
		setBlock(world, random, x + 1, y + 5, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 5, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 5, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 5, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 5, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 5, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 5, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 5, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 5, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 5, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 0, y + 5, z + 7, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 1, y + 5, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 5, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 5, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 5, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 5, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 5, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 5, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 5, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 5, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 5, z + 7, Blocks.stone, 0, 3);
		setBlock(world, random, x + 0, y + 5, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 5, z + 8, Blocks.stone, 0, 3);
		setBlock(world, random, x + 2, y + 5, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 5, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 5, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 5, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 5, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 5, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 5, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 5, z + 8, Blocks.stone, 0, 3);
		setBlock(world, random, x + 10, y + 5, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 5, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 5, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 5, z + 9, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 3, y + 5, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 5, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 5, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 5, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 5, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 5, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 9, y + 5, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 5, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 5, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 5, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 5, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 5, z + 10, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 4, y + 5, z + 10, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 5, y + 5, z + 10, Blocks.stone, 0, 3);
		setBlock(world, random, x + 6, y + 5, z + 10, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 7, y + 5, z + 10, Blocks.stone, 0, 3);
		setBlock(world, random, x + 8, y + 5, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 5, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 5, z + 10, Blocks.air, 0, 3);

		running = false; // Half built, let another thread start now

		// Upper level, from part2 of schematic
		// 13 wide (x) x 13 length (z)
		new EasyMobDungeon1_part2().generate_part2(world, random, x - 1 , y + 6, z - 1);

		//adding a chest with random stuff
		// If just one chest, set last two parameters to 1 and false
		generateChest(world, random, x + 7, y + 1, z + 1, 3, 1, false);	
		
		// Mob spawner
		generateMobSpawner(world, random, x + 2, y + 1, z + 2, 0);		
		generateMobSpawner(world, random, x + 7, y + 1, z + 9, 0);		
	}
}
