package com.thexfactor117.ascension.structures;

import java.util.Random;

import com.thexfactor117.ascension.help.LogHelper;

import net.minecraft.init.Blocks;
import net.minecraft.world.World;

/**
 * 
 * @author WILLIAM
 *
 */
public class EasyMobDungeon1_part2 extends EasyMobDungeon1 {

	// Upper level, from part2 of schematic
	// 13 wide (x) x 13 length (z)
	public void generate_part2(World world, Random random, int x, int y, int z) {
//		setBlock(world, random, x + 0, y + 0, z + 0, Blocks.air, 0, 3);
		LogHelper.info("Generating Easy Mob Dungeon 1, part 2 at " + x + "," + y + "," + z + "!");
		setBlock(world, random, x + 0, y + 0, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 0, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 0, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 0, z + 0, Blocks.stone_brick_stairs, 4, 3);
		setBlock(world, random, x + 4, y + 0, z + 0, Blocks.stone_stairs, 6, 3);
		setBlock(world, random, x + 5, y + 0, z + 0, Blocks.stone_stairs, 6, 3);
		setBlock(world, random, x + 6, y + 0, z + 0, Blocks.stone_brick_stairs, 6, 3);
		setBlock(world, random, x + 7, y + 0, z + 0, Blocks.stone_stairs, 6, 3);
		setBlock(world, random, x + 8, y + 0, z + 0, Blocks.stone_brick_stairs, 6, 3);
		setBlock(world, random, x + 9, y + 0, z + 0, Blocks.stone_brick_stairs, 6, 3);
		setBlock(world, random, x + 10, y + 0, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 11, y + 0, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 12, y + 0, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 0, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 0, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 0, z + 1, Blocks.stone_stairs, 4, 3);
		setBlock(world, random, x + 3, y + 0, z + 1, Blocks.stone_brick_stairs, 6, 3);
		setBlock(world, random, x + 4, y + 0, z + 1, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 5, y + 0, z + 1, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 6, y + 0, z + 1, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 7, y + 0, z + 1, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 8, y + 0, z + 1, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 9, y + 0, z + 1, Blocks.stone_brick_stairs, 5, 3);
		setBlock(world, random, x + 10, y + 0, z + 1, Blocks.stone_stairs, 6, 3);
		setBlock(world, random, x + 11, y + 0, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 12, y + 0, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 0, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 0, z + 2, Blocks.stone_stairs, 4, 3);
		setBlock(world, random, x + 2, y + 0, z + 2, Blocks.stone_brick_stairs, 6, 3);
		setBlock(world, random, x + 3, y + 0, z + 2, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 4, y + 0, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 0, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 0, z + 2, Blocks.stone, 0, 3);
		setBlock(world, random, x + 7, y + 0, z + 2, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 8, y + 0, z + 2, Blocks.stone, 0, 3);
		setBlock(world, random, x + 9, y + 0, z + 2, Blocks.stone, 0, 3);
		setBlock(world, random, x + 10, y + 0, z + 2, Blocks.stone_stairs, 5, 3);
		setBlock(world, random, x + 11, y + 0, z + 2, Blocks.stone_brick_stairs, 6, 3);
		setBlock(world, random, x + 12, y + 0, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 0, z + 3, Blocks.stone_stairs, 6, 3);
		setBlock(world, random, x + 1, y + 0, z + 3, Blocks.stone_stairs, 4, 3);
		setBlock(world, random, x + 2, y + 0, z + 3, Blocks.stone, 0, 3);
		setBlock(world, random, x + 3, y + 0, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 0, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 0, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 0, z + 3, Blocks.stone, 0, 3);
		setBlock(world, random, x + 7, y + 0, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 8, y + 0, z + 3, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 9, y + 0, z + 3, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 10, y + 0, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 11, y + 0, z + 3, Blocks.stone_stairs, 5, 3);
		setBlock(world, random, x + 12, y + 0, z + 3, Blocks.stone_stairs, 6, 3);
		setBlock(world, random, x + 0, y + 0, z + 4, Blocks.stone_brick_stairs, 4, 3);
		setBlock(world, random, x + 1, y + 0, z + 4, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 2, y + 0, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 0, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 0, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 6, y + 0, z + 4, Blocks.stone, 0, 3);
		setBlock(world, random, x + 7, y + 0, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 0, z + 4, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 9, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 10, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 11, y + 0, z + 4, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 12, y + 0, z + 4, Blocks.stone_brick_stairs, 5, 3);
		setBlock(world, random, x + 0, y + 0, z + 5, Blocks.stone_stairs, 4, 3);
		setBlock(world, random, x + 1, y + 0, z + 5, Blocks.stone, 0, 3);
		setBlock(world, random, x + 2, y + 0, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 0, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 0, z + 5, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 5, y + 0, z + 5, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 6, y + 0, z + 5, Blocks.stone, 0, 3);
		setBlock(world, random, x + 7, y + 0, z + 5, Blocks.stone, 0, 3);
		setBlock(world, random, x + 8, y + 0, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 9, y + 0, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 10, y + 0, z + 5, Blocks.stone, 0, 3);
		setBlock(world, random, x + 11, y + 0, z + 5, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 12, y + 0, z + 5, Blocks.stone_stairs, 5, 3);
		setBlock(world, random, x + 0, y + 0, z + 6, Blocks.stone_brick_stairs, 4, 3);
		setBlock(world, random, x + 1, y + 0, z + 6, Blocks.stone, 0, 3);
		setBlock(world, random, x + 2, y + 0, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 3, y + 0, z + 6, Blocks.stone, 0, 3);
		setBlock(world, random, x + 4, y + 0, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 5, y + 0, z + 6, Blocks.stone, 0, 3);
		setBlock(world, random, x + 6, y + 0, z + 6, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 7, y + 0, z + 6, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 8, y + 0, z + 6, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 9, y + 0, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 0, z + 6, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 11, y + 0, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 12, y + 0, z + 6, Blocks.stone_brick_stairs, 5, 3);
		setBlock(world, random, x + 0, y + 0, z + 7, Blocks.stone_brick_stairs, 4, 3);
		setBlock(world, random, x + 1, y + 0, z + 7, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 2, y + 0, z + 7, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 3, y + 0, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 4, y + 0, z + 7, Blocks.stone, 0, 3);
		setBlock(world, random, x + 5, y + 0, z + 7, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 6, y + 0, z + 7, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 7, y + 0, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 8, y + 0, z + 7, Blocks.stone, 0, 3);
		setBlock(world, random, x + 9, y + 0, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 10, y + 0, z + 7, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 11, y + 0, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 12, y + 0, z + 7, Blocks.stone_stairs, 5, 3);
		
		preventLag();

		setBlock(world, random, x + 0, y + 0, z + 8, Blocks.stone_brick_stairs, 4, 3);
		setBlock(world, random, x + 1, y + 0, z + 8, Blocks.stone, 0, 3);
		setBlock(world, random, x + 2, y + 0, z + 8, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 3, y + 0, z + 8, Blocks.stone, 0, 3);
		setBlock(world, random, x + 4, y + 0, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 0, z + 8, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 6, y + 0, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 7, y + 0, z + 8, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 8, y + 0, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 9, y + 0, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 10, y + 0, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 11, y + 0, z + 8, Blocks.stone, 0, 3);
		setBlock(world, random, x + 12, y + 0, z + 8, Blocks.stone_brick_stairs, 5, 3);
		setBlock(world, random, x + 0, y + 0, z + 9, Blocks.stone_stairs, 7, 3);
		setBlock(world, random, x + 1, y + 0, z + 9, Blocks.stone_stairs, 4, 3);
		setBlock(world, random, x + 2, y + 0, z + 9, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 3, y + 0, z + 9, Blocks.stone, 0, 3);
		setBlock(world, random, x + 4, y + 0, z + 9, Blocks.stone, 0, 3);
		setBlock(world, random, x + 5, y + 0, z + 9, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 6, y + 0, z + 9, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 7, y + 0, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 0, z + 9, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 9, y + 0, z + 9, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 10, y + 0, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 11, y + 0, z + 9, Blocks.stone_brick_stairs, 5, 3);
		setBlock(world, random, x + 12, y + 0, z + 9, Blocks.stone_stairs, 7, 3);
		setBlock(world, random, x + 0, y + 0, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 0, z + 10, Blocks.stone_stairs, 7, 3);
		setBlock(world, random, x + 2, y + 0, z + 10, Blocks.stone_brick_stairs, 4, 3);
		setBlock(world, random, x + 3, y + 0, z + 10, Blocks.stone, 0, 3);
		setBlock(world, random, x + 4, y + 0, z + 10, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 5, y + 0, z + 10, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 6, y + 0, z + 10, Blocks.stone, 0, 3);
		setBlock(world, random, x + 7, y + 0, z + 10, Blocks.stone, 0, 3);
		setBlock(world, random, x + 8, y + 0, z + 10, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 9, y + 0, z + 10, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 10, y + 0, z + 10, Blocks.stone_stairs, 7, 3);
		setBlock(world, random, x + 11, y + 0, z + 10, Blocks.stone_stairs, 5, 3);
		setBlock(world, random, x + 12, y + 0, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 0, z + 11, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 0, z + 11, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 0, z + 11, Blocks.stone_stairs, 7, 3);
		setBlock(world, random, x + 3, y + 0, z + 11, Blocks.stone_brick_stairs, 4, 3);
		setBlock(world, random, x + 4, y + 0, z + 11, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 5, y + 0, z + 11, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 6, y + 0, z + 11, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 7, y + 0, z + 11, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 8, y + 0, z + 11, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 9, y + 0, z + 11, Blocks.stone_brick_stairs, 7, 3);
		setBlock(world, random, x + 10, y + 0, z + 11, Blocks.stone_stairs, 5, 3);
		setBlock(world, random, x + 11, y + 0, z + 11, Blocks.air, 0, 3);
		setBlock(world, random, x + 12, y + 0, z + 11, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 0, z + 12, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 0, z + 12, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 0, z + 12, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 0, z + 12, Blocks.stone_stairs, 7, 3);
		setBlock(world, random, x + 4, y + 0, z + 12, Blocks.stone_brick_stairs, 7, 3);
		setBlock(world, random, x + 5, y + 0, z + 12, Blocks.stone_stairs, 7, 3);
		setBlock(world, random, x + 6, y + 0, z + 12, Blocks.stone_stairs, 7, 3);
		setBlock(world, random, x + 7, y + 0, z + 12, Blocks.stone_brick_stairs, 7, 3);
		setBlock(world, random, x + 8, y + 0, z + 12, Blocks.stone_brick_stairs, 7, 3);
		setBlock(world, random, x + 9, y + 0, z + 12, Blocks.stone_stairs, 5, 3);
		setBlock(world, random, x + 10, y + 0, z + 12, Blocks.air, 0, 3);
		setBlock(world, random, x + 11, y + 0, z + 12, Blocks.air, 0, 3);
		setBlock(world, random, x + 12, y + 0, z + 12, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 1, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 1, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 1, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 0, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 0, Blocks.stone, 0, 3);
		setBlock(world, random, x + 5, y + 1, z + 0, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 6, y + 1, z + 0, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 7, y + 1, z + 0, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 8, y + 1, z + 0, Blocks.stone, 0, 3);
		setBlock(world, random, x + 9, y + 1, z + 0, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 10, y + 1, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 11, y + 1, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 12, y + 1, z + 0, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 1, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 1, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 1, z + 1, Blocks.stone, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 1, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 1, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 1, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 1, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 1, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 1, z + 1, Blocks.stone, 0, 3);
		setBlock(world, random, x + 11, y + 1, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 12, y + 1, z + 1, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 1, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 1, z + 2, Blocks.stone, 0, 3);
		setBlock(world, random, x + 2, y + 1, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 1, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 1, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 1, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 1, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 1, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 1, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 11, y + 1, z + 2, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 12, y + 1, z + 2, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 1, z + 3, Blocks.stone, 0, 3);
		setBlock(world, random, x + 1, y + 1, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 1, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 1, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 1, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 1, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 1, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 1, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 1, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 11, y + 1, z + 3, Blocks.air, 0, 3);
		setBlock(world, random, x + 12, y + 1, z + 3, Blocks.stone, 0, 3);
		setBlock(world, random, x + 0, y + 1, z + 4, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 1, y + 1, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 1, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 1, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 1, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 1, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 1, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 1, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 1, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 11, y + 1, z + 4, Blocks.air, 0, 3);
		setBlock(world, random, x + 12, y + 1, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 0, y + 1, z + 5, Blocks.stone, 0, 3);
		setBlock(world, random, x + 1, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 11, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, random, x + 12, y + 1, z + 5, Blocks.stone, 0, 3);
		setBlock(world, random, x + 0, y + 1, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 1, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 1, z + 6, Blocks.air, 0, 3);
//		setBlock(world, random, x + 6, y + 1, z + 6, Blocks.mob_spawner, 0, 3);
		setBlock(world, random, x + 7, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 11, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, random, x + 12, y + 1, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 0, y + 1, z + 7, Blocks.stone, 0, 3);
		setBlock(world, random, x + 1, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 11, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, random, x + 12, y + 1, z + 7, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 0, y + 1, z + 8, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 1, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 11, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, random, x + 12, y + 1, z + 8, Blocks.stone, 0, 3);
		setBlock(world, random, x + 0, y + 1, z + 9, Blocks.cobblestone, 0, 3);
//		setBlock(world, random, x + 1, y + 1, z + 9, Blocks.chest, 5, 3);
		setBlock(world, random, x + 2, y + 1, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 1, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 1, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 1, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 1, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 1, z + 9, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 1, z + 9, Blocks.air, 0, 3);
//		setBlock(world, random, x + 11, y + 1, z + 9, Blocks.chest, 4, 3);
		setBlock(world, random, x + 12, y + 1, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, random, x + 0, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 1, z + 10, Blocks.stone, 0, 3);
		setBlock(world, random, x + 2, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 11, y + 1, z + 10, Blocks.stone, 0, 3);
		setBlock(world, random, x + 12, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 1, z + 11, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 1, z + 11, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 1, z + 11, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 11, Blocks.air, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 11, Blocks.air, 0, 3);
		setBlock(world, random, x + 5, y + 1, z + 11, Blocks.air, 0, 3);
		setBlock(world, random, x + 6, y + 1, z + 11, Blocks.air, 0, 3);
		setBlock(world, random, x + 7, y + 1, z + 11, Blocks.air, 0, 3);
		setBlock(world, random, x + 8, y + 1, z + 11, Blocks.air, 0, 3);
		setBlock(world, random, x + 9, y + 1, z + 11, Blocks.air, 0, 3);
		setBlock(world, random, x + 10, y + 1, z + 11, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 11, y + 1, z + 11, Blocks.air, 0, 3);
		setBlock(world, random, x + 12, y + 1, z + 11, Blocks.air, 0, 3);
		setBlock(world, random, x + 0, y + 1, z + 12, Blocks.air, 0, 3);
		setBlock(world, random, x + 1, y + 1, z + 12, Blocks.air, 0, 3);
		setBlock(world, random, x + 2, y + 1, z + 12, Blocks.air, 0, 3);
		setBlock(world, random, x + 3, y + 1, z + 12, Blocks.stone, 0, 3);
		setBlock(world, random, x + 4, y + 1, z + 12, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 5, y + 1, z + 12, Blocks.stone, 0, 3);
		setBlock(world, random, x + 6, y + 1, z + 12, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 7, y + 1, z + 12, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 8, y + 1, z + 12, Blocks.stonebrick, 0, 3);
		setBlock(world, random, x + 9, y + 1, z + 12, Blocks.stone, 0, 3);
		setBlock(world, random, x + 10, y + 1, z + 12, Blocks.air, 0, 3);
		setBlock(world, random, x + 11, y + 1, z + 12, Blocks.air, 0, 3);
		setBlock(world, random, x + 12, y + 1, z + 12, Blocks.air, 0, 3);

		// Generate random chest location, one of the 4 locations below, setting the last chance to 1, 
		// guarantees 1 chest
		int numChests = 2;
		boolean generatedChest = false;
		generatedChest = generateChest(world, random, x + 1, y + 1, z + 9, 5, numChests, generatedChest);
		generatedChest = generateChest(world, random, x + 11, y + 1, z + 9, 4, numChests, generatedChest);

		// Mob spawner
		generateMobSpawner(world, random, x + 6, y + 1, z + 6, 0);		
	}
}
