//Schematic to java Structure by jajo_11 | inspired by "MITHION'S .SCHEMATIC TO JAVA CONVERTINGTOOL"

package com.thexfactor117.ascension.structures;

import java.util.Random;

import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.world.World;

import com.thexfactor117.ascension.help.LogHelper;

/**
 * 
 * @author WILLIAM
 *
 */
public class SkyrimStyleHouse0 extends AbandonedStructure
{
	// Variables for configuration
	public static int missingBlockChance = 1;    // 1/n chance of setting block, set not less than 1, to 1 to set all blocks
	public static int spawnHeightTolerance = 6;   // Set larger for bigger structures
	public static int spawnChance = 80;           // chance n/1000
	
	public SkyrimStyleHouse0() 
	{
		structureMissingBlockChance = missingBlockChance;
		structureSpawnHeightTolerance = spawnHeightTolerance;
		structureSpawnChance = spawnChance;
		validSpawnBlocks = GetValidSpawnBlocks();
		// Add these in order of low to high probability:
		addRandomChestItem(Items.arrow, 1, 3, 10);
		addRandomChestItem(Items.apple, 1, 3, 20);
	}

	protected Block[] GetValidSpawnBlocks()
	{
		return new Block[]
		{
			Blocks.grass,
			Blocks.dirt,
			Blocks.stone,
			Blocks.cobblestone,
			Blocks.sand,
			Blocks.gravel,
			Blocks.sandstone,
		};
	}

	@Override
	public boolean generate(World world, Random random, int x, int y, int z) {
		// Add this line to prevent more than one being built at a time
		if (running) return false; 

		//check that each corner is one of the valid spawn blocks
		if(!locationIsValidSpawn(world, x, y, z) 
				|| !locationIsValidSpawn(world, x + 18, y, z) 
				|| !locationIsValidSpawn(world, x + 18, y, z + 18) 
				|| !locationIsValidSpawn(world, x, y, z + 18))
		{
			return false;
		}
		LogHelper.info("Generating a Skyrim Style House at " + x + "," + y + "," + z + "!");

		// Alternate way to create a large structure in a separate thread (with base)
		generateStructureInThread(world, random, x, y, z, 3, 3, 18, 18, true);
		
		return true;
	}

	public void generateStructure(World world, Random rand, int x, int y, int z)
	{
		floorLevel = y - 1; // Prevents any blocks from being removed at this level

		// Entrance
		setBlock(world, rand, x + 9, y + -1, z + 16, Blocks.cobblestone, 0, 3);

		// Generate random chest location, one of the 4 locations below, setting the last chance to 1, 
		// guarantees 1 chest
		int numChests = 4;
		boolean generatedChest = false;
		generatedChest = generateChest(world, rand, x + 4, y + 4, z + 4, 2, numChests, generatedChest);
		generatedChest = generateChest(world, rand, x + 14, y + 4, z + 4, 2, numChests, generatedChest);
		generatedChest = generateChest(world, rand, x + 4, y + 4, z + 14, 2, numChests, generatedChest);
		generatedChest = generateChest(world, rand, x + 14, y + 4, z + 14, 2, 1, generatedChest);

//		setBlock(world, rand, x + 4, y + 4, z + 4, Blocks.chest, 3, 3);
//		setBlock(world, rand, x + 14, y + 4, z + 4, Blocks.chest, 4, 3);
//		setBlock(world, rand, x + 4, y + 4, z + 14, Blocks.chest, 5, 3);
//		setBlock(world, rand, x + 14, y + 4, z + 14, Blocks.chest, 2, 3);

//		setBlock(world, rand, x + 0, y + -1, z + 0, Blocks.sand, 1, 3);
//		setBlock(world, rand, x + 1, y + -1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + -1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + -1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 4, y + -1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 5, y + -1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 6, y + -1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 7, y + -1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 8, y + -1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 9, y + -1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 10, y + -1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 11, y + -1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 12, y + -1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 13, y + -1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 14, y + -1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 15, y + -1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + -1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + -1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + -1, z + 0, Blocks.sand, 0, 3);
//		setBlock(world, rand, x + 0, y + -1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + -1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + -1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + -1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 4, y + -1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 5, y + -1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 6, y + -1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 7, y + -1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 8, y + -1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 9, y + -1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 10, y + -1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 11, y + -1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 12, y + -1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 13, y + -1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 14, y + -1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 15, y + -1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + -1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + -1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + -1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + -1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + -1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + -1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + -1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 4, y + -1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 5, y + -1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 6, y + -1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 7, y + -1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 8, y + -1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 9, y + -1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 10, y + -1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 11, y + -1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 12, y + -1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 13, y + -1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 14, y + -1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 15, y + -1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + -1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + -1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + -1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + -1, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + -1, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + -1, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + -1, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 4, y + -1, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 5, y + -1, z + 3, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 6, y + -1, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + -1, z + 3, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 8, y + -1, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + -1, z + 3, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 10, y + -1, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + -1, z + 3, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 12, y + -1, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + -1, z + 3, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 14, y + -1, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 15, y + -1, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + -1, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + -1, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + -1, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + -1, z + 4, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + -1, z + 4, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + -1, z + 4, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + -1, z + 4, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + -1, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + -1, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 6, y + -1, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 7, y + -1, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 8, y + -1, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 9, y + -1, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 10, y + -1, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 11, y + -1, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 12, y + -1, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 13, y + -1, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 14, y + -1, z + 4, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 15, y + -1, z + 4, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + -1, z + 4, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + -1, z + 4, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + -1, z + 4, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + -1, z + 5, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + -1, z + 5, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + -1, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + -1, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 4, y + -1, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + -1, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 6, y + -1, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 7, y + -1, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 8, y + -1, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 9, y + -1, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 10, y + -1, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 11, y + -1, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 12, y + -1, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 13, y + -1, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 14, y + -1, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + -1, z + 5, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 16, y + -1, z + 5, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + -1, z + 5, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + -1, z + 5, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + -1, z + 6, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + -1, z + 6, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + -1, z + 6, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + -1, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + -1, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + -1, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 6, y + -1, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 7, y + -1, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 8, y + -1, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 9, y + -1, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 10, y + -1, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 11, y + -1, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 12, y + -1, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 13, y + -1, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 14, y + -1, z + 6, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 15, y + -1, z + 6, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + -1, z + 6, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + -1, z + 6, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + -1, z + 6, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + -1, z + 7, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + -1, z + 7, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + -1, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + -1, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 4, y + -1, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + -1, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 6, y + -1, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 7, y + -1, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 8, y + -1, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 9, y + -1, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 10, y + -1, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 11, y + -1, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 12, y + -1, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 13, y + -1, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 14, y + -1, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + -1, z + 7, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 16, y + -1, z + 7, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + -1, z + 7, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + -1, z + 7, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + -1, z + 8, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + -1, z + 8, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + -1, z + 8, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + -1, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + -1, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + -1, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 6, y + -1, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 7, y + -1, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 8, y + -1, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 9, y + -1, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 10, y + -1, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 11, y + -1, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 12, y + -1, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 13, y + -1, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 14, y + -1, z + 8, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 15, y + -1, z + 8, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + -1, z + 8, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + -1, z + 8, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + -1, z + 8, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + -1, z + 9, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + -1, z + 9, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + -1, z + 9, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + -1, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 4, y + -1, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + -1, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 6, y + -1, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 7, y + -1, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 8, y + -1, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 9, y + -1, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 10, y + -1, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 11, y + -1, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 12, y + -1, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 13, y + -1, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 14, y + -1, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + -1, z + 9, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 16, y + -1, z + 9, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + -1, z + 9, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + -1, z + 9, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + -1, z + 10, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + -1, z + 10, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + -1, z + 10, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + -1, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + -1, z + 10, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + -1, z + 10, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 6, y + -1, z + 10, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 7, y + -1, z + 10, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 8, y + -1, z + 10, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 9, y + -1, z + 10, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 10, y + -1, z + 10, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 11, y + -1, z + 10, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 12, y + -1, z + 10, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 13, y + -1, z + 10, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 14, y + -1, z + 10, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 15, y + -1, z + 10, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + -1, z + 10, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + -1, z + 10, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + -1, z + 10, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + -1, z + 11, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + -1, z + 11, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + -1, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + -1, z + 11, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 4, y + -1, z + 11, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + -1, z + 11, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 6, y + -1, z + 11, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 7, y + -1, z + 11, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 8, y + -1, z + 11, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 9, y + -1, z + 11, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 10, y + -1, z + 11, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 11, y + -1, z + 11, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 12, y + -1, z + 11, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 13, y + -1, z + 11, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 14, y + -1, z + 11, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + -1, z + 11, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 16, y + -1, z + 11, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + -1, z + 11, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + -1, z + 11, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + -1, z + 12, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + -1, z + 12, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + -1, z + 12, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + -1, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + -1, z + 12, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + -1, z + 12, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 6, y + -1, z + 12, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 7, y + -1, z + 12, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 8, y + -1, z + 12, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 9, y + -1, z + 12, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 10, y + -1, z + 12, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 11, y + -1, z + 12, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 12, y + -1, z + 12, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 13, y + -1, z + 12, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 14, y + -1, z + 12, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 15, y + -1, z + 12, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + -1, z + 12, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + -1, z + 12, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + -1, z + 12, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + -1, z + 13, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + -1, z + 13, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + -1, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + -1, z + 13, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 4, y + -1, z + 13, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + -1, z + 13, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 6, y + -1, z + 13, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 7, y + -1, z + 13, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 8, y + -1, z + 13, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 9, y + -1, z + 13, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 10, y + -1, z + 13, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 11, y + -1, z + 13, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 12, y + -1, z + 13, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 13, y + -1, z + 13, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 14, y + -1, z + 13, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + -1, z + 13, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 16, y + -1, z + 13, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + -1, z + 13, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + -1, z + 13, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + -1, z + 14, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + -1, z + 14, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + -1, z + 14, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + -1, z + 14, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + -1, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + -1, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 6, y + -1, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 7, y + -1, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 8, y + -1, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 9, y + -1, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 10, y + -1, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 11, y + -1, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 12, y + -1, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 13, y + -1, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 14, y + -1, z + 14, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 15, y + -1, z + 14, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + -1, z + 14, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + -1, z + 14, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + -1, z + 14, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + -1, z + 15, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + -1, z + 15, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + -1, z + 15, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + -1, z + 15, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 4, y + -1, z + 15, Blocks.air, 0, 3);
		setBlock(world, rand, x + 5, y + -1, z + 15, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 6, y + -1, z + 15, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + -1, z + 15, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 8, y + -1, z + 15, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 9, y + -1, z + 15, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 10, y + -1, z + 15, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 11, y + -1, z + 15, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 12, y + -1, z + 15, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + -1, z + 15, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 14, y + -1, z + 15, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 15, y + -1, z + 15, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + -1, z + 15, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + -1, z + 15, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + -1, z + 15, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + -1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + -1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + -1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + -1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 4, y + -1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 5, y + -1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 6, y + -1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 7, y + -1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 8, y + -1, z + 16, Blocks.air, 0, 3);

		// Entrance
//		setBlock(world, rand, x + 9, y + -1, z + 16, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 10, y + -1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 11, y + -1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 12, y + -1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 13, y + -1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 14, y + -1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 15, y + -1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + -1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + -1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + -1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + -1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + -1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + -1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + -1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 4, y + -1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 5, y + -1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 6, y + -1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 7, y + -1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 8, y + -1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 9, y + -1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 10, y + -1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 11, y + -1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 12, y + -1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 13, y + -1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 14, y + -1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 15, y + -1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + -1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + -1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + -1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + -1, z + 18, Blocks.sand, 0, 3);
//		setBlock(world, rand, x + 1, y + -1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + -1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + -1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 4, y + -1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 5, y + -1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 6, y + -1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 7, y + -1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 8, y + -1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 9, y + -1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 10, y + -1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 11, y + -1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 12, y + -1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 13, y + -1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 14, y + -1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 15, y + -1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + -1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + -1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + -1, z + 18, Blocks.sand, 0, 3);

//		setBlock(world, rand, x + 0, y + 0, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 0, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 0, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + 0, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 4, y + 0, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 5, y + 0, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 6, y + 0, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 7, y + 0, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 8, y + 0, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 9, y + 0, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 10, y + 0, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 11, y + 0, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 12, y + 0, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 13, y + 0, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 14, y + 0, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 15, y + 0, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + 0, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 0, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 0, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 0, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 0, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 0, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + 0, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 4, y + 0, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 5, y + 0, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 6, y + 0, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 7, y + 0, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 8, y + 0, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 9, y + 0, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 10, y + 0, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 11, y + 0, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 12, y + 0, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 13, y + 0, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 14, y + 0, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 15, y + 0, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + 0, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 0, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 0, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 0, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 0, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 0, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + 0, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 4, y + 0, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 5, y + 0, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 6, y + 0, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 7, y + 0, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 8, y + 0, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 9, y + 0, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 10, y + 0, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 11, y + 0, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 12, y + 0, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 13, y + 0, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 14, y + 0, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 15, y + 0, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + 0, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 0, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 0, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 0, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 0, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 0, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + 0, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 4, y + 0, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 5, y + 0, z + 3, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 6, y + 0, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 0, z + 3, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 8, y + 0, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 0, z + 3, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 10, y + 0, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 0, z + 3, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 12, y + 0, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + 0, z + 3, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 14, y + 0, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 15, y + 0, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + 0, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 0, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 0, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 0, z + 4, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 0, z + 4, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 0, z + 4, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + 0, z + 4, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 6, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 7, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 8, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 9, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 10, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 11, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 12, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 13, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 14, y + 0, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + 0, z + 4, Blocks.air, 0, 3);
		setBlock(world, rand, x + 16, y + 0, z + 4, Blocks.air, 0, 3);
		setBlock(world, rand, x + 17, y + 0, z + 4, Blocks.air, 0, 3);
		setBlock(world, rand, x + 18, y + 0, z + 4, Blocks.air, 0, 3);
		setBlock(world, rand, x + 0, y + 0, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 1, y + 0, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 2, y + 0, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + 0, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 4, y + 0, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + 0, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 6, y + 0, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 0, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 8, y + 0, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 0, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 10, y + 0, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 0, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 12, y + 0, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + 0, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 14, y + 0, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + 0, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 16, y + 0, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 17, y + 0, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 18, y + 0, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 0, y + 0, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 1, y + 0, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 2, y + 0, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + 0, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + 0, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + 0, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 6, y + 0, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 0, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 8, y + 0, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 0, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 10, y + 0, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 0, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 12, y + 0, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + 0, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 14, y + 0, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + 0, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 16, y + 0, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 17, y + 0, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 18, y + 0, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 0, y + 0, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 1, y + 0, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 2, y + 0, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + 0, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 4, y + 0, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + 0, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 6, y + 0, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 0, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 8, y + 0, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 0, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 10, y + 0, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 0, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 12, y + 0, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + 0, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 14, y + 0, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + 0, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 16, y + 0, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 17, y + 0, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 18, y + 0, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 0, y + 0, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 1, y + 0, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 2, y + 0, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + 0, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + 0, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + 0, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 6, y + 0, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 0, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 8, y + 0, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 0, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 10, y + 0, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 0, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 12, y + 0, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + 0, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 14, y + 0, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + 0, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 16, y + 0, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 17, y + 0, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 18, y + 0, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 0, y + 0, z + 9, Blocks.air, 0, 3);
		setBlock(world, rand, x + 1, y + 0, z + 9, Blocks.air, 0, 3);
		setBlock(world, rand, x + 2, y + 0, z + 9, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + 0, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 4, y + 0, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 6, y + 0, z + 9, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 0, z + 9, Blocks.air, 0, 3);
		setBlock(world, rand, x + 8, y + 0, z + 9, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 0, z + 9, Blocks.air, 0, 3);
		setBlock(world, rand, x + 10, y + 0, z + 9, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 0, z + 9, Blocks.air, 0, 3);
		setBlock(world, rand, x + 12, y + 0, z + 9, Blocks.air, 0, 3);
		setBlock(world, rand, x + 14, y + 0, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + 0, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 16, y + 0, z + 9, Blocks.air, 0, 3);
		setBlock(world, rand, x + 17, y + 0, z + 9, Blocks.air, 0, 3);
		setBlock(world, rand, x + 18, y + 0, z + 9, Blocks.air, 0, 3);
		setBlock(world, rand, x + 0, y + 0, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 1, y + 0, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 2, y + 0, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + 0, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + 0, z + 10, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + 0, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 6, y + 0, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 0, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 8, y + 0, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 0, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 10, y + 0, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 0, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 12, y + 0, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + 0, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 14, y + 0, z + 10, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + 0, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 16, y + 0, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 17, y + 0, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 18, y + 0, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 0, y + 0, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 1, y + 0, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 2, y + 0, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + 0, z + 11, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 4, y + 0, z + 11, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + 0, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 6, y + 0, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 0, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 8, y + 0, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 0, z + 11, Blocks.air, 0, 3);
		
		preventLag();

		setBlock(world, rand, x + 10, y + 0, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 0, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 12, y + 0, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + 0, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 14, y + 0, z + 11, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + 0, z + 11, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 16, y + 0, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 17, y + 0, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 18, y + 0, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 0, y + 0, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 1, y + 0, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 2, y + 0, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + 0, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + 0, z + 12, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + 0, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 6, y + 0, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 0, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 8, y + 0, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 0, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 10, y + 0, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 0, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 12, y + 0, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + 0, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 14, y + 0, z + 12, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + 0, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 16, y + 0, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 17, y + 0, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 18, y + 0, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 0, y + 0, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 1, y + 0, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 2, y + 0, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + 0, z + 13, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 4, y + 0, z + 13, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + 0, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 6, y + 0, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 0, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 8, y + 0, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 0, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 10, y + 0, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 0, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 12, y + 0, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + 0, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 14, y + 0, z + 13, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + 0, z + 13, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 16, y + 0, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 17, y + 0, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 18, y + 0, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 0, y + 0, z + 14, Blocks.air, 0, 3);
		setBlock(world, rand, x + 1, y + 0, z + 14, Blocks.air, 0, 3);
		setBlock(world, rand, x + 2, y + 0, z + 14, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + 0, z + 14, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + 0, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + 0, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 6, y + 0, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 7, y + 0, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 8, y + 0, z + 14, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 9, y + 0, z + 14, Blocks.wooden_door, 3, 3);
		setBlock(world, rand, x + 10, y + 0, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 11, y + 0, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 12, y + 0, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 13, y + 0, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 14, y + 0, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + 0, z + 14, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + 0, z + 14, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 0, z + 14, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 0, z + 14, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 0, z + 15, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 0, z + 15, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 0, z + 15, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + 0, z + 15, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + 0, z + 15, Blocks.air, 0, 3);
		setBlock(world, rand, x + 5, y + 0, z + 15, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 6, y + 0, z + 15, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 0, z + 15, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 8, y + 0, z + 15, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 0, z + 15, Blocks.air, 0, 3);
		setBlock(world, rand, x + 10, y + 0, z + 15, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 0, z + 15, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 12, y + 0, z + 15, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + 0, z + 15, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 14, y + 0, z + 15, Blocks.air, 0, 3);
		setBlock(world, rand, x + 15, y + 0, z + 15, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + 0, z + 15, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 0, z + 15, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 0, z + 15, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 0, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 0, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 0, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + 0, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 4, y + 0, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 5, y + 0, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 6, y + 0, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 7, y + 0, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 8, y + 0, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 9, y + 0, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 10, y + 0, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 11, y + 0, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 12, y + 0, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 13, y + 0, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 14, y + 0, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 15, y + 0, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + 0, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 0, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 0, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 0, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 0, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 0, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + 0, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 4, y + 0, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 5, y + 0, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 6, y + 0, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 7, y + 0, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 8, y + 0, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 9, y + 0, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 10, y + 0, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 11, y + 0, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 12, y + 0, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 13, y + 0, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 14, y + 0, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 15, y + 0, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + 0, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 0, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 0, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 0, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 0, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 0, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + 0, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 4, y + 0, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 5, y + 0, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 6, y + 0, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 7, y + 0, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 8, y + 0, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 9, y + 0, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 10, y + 0, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 11, y + 0, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 12, y + 0, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 13, y + 0, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 14, y + 0, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 15, y + 0, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + 0, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 0, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 0, z + 18, Blocks.air, 0, 3);

//		setBlock(world, rand, x + 0, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 4, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 5, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 6, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 7, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 8, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 9, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 10, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 11, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 12, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 13, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 14, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 15, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 1, z + 0, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 4, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 5, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 6, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 7, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 8, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 9, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 10, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 11, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 12, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 13, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 14, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 15, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 1, z + 1, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + 1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 4, y + 1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 5, y + 1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 6, y + 1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 7, y + 1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 8, y + 1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 9, y + 1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 10, y + 1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 11, y + 1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 12, y + 1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 13, y + 1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 14, y + 1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 15, y + 1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + 1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 1, z + 2, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 1, z + 2, Blocks.air, 0, 3);

//		setBlock(world, rand, x + 0, y + 1, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 1, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 1, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + 1, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 5, y + 1, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 7, y + 1, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 9, y + 1, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 11, y + 1, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 13, y + 1, z + 3, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 15, y + 1, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + 1, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 1, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 1, z + 3, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 1, z + 4, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 1, z + 4, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 1, z + 4, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + 1, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + 1, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 6, y + 1, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 7, y + 1, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 8, y + 1, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 9, y + 1, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 10, y + 1, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 11, y + 1, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 12, y + 1, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 13, y + 1, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 14, y + 1, z + 4, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 16, y + 1, z + 4, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 1, z + 4, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 1, z + 4, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 1, z + 5, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 1, z + 5, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + 1, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 4, y + 1, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 6, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 8, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 10, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 12, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + 1, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 14, y + 1, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + 1, z + 5, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 16, y + 1, z + 5, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 1, z + 5, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 1, z + 5, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 1, z + 6, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 1, z + 6, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + 1, z + 6, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 6, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 8, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 10, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 12, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + 1, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 14, y + 1, z + 6, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 16, y + 1, z + 6, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 1, z + 6, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 1, z + 6, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 1, z + 7, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 1, z + 7, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + 1, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 4, y + 1, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 6, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 8, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 10, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 12, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + 1, z + 7, Blocks.air, 0, 3);
		setBlock(world, rand, x + 14, y + 1, z + 7, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + 1, z + 7, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 16, y + 1, z + 7, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 1, z + 7, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 1, z + 7, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 1, z + 8, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 1, z + 8, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + 1, z + 8, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 6, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 8, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 10, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 12, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + 1, z + 8, Blocks.air, 0, 3);
		setBlock(world, rand, x + 14, y + 1, z + 8, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 16, y + 1, z + 8, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 1, z + 8, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 1, z + 8, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 1, z + 9, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 1, z + 9, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 1, z + 9, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + 1, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 4, y + 1, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 6, y + 1, z + 9, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 1, z + 9, Blocks.air, 0, 3);
		setBlock(world, rand, x + 8, y + 1, z + 9, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 1, z + 9, Blocks.air, 0, 3);
		setBlock(world, rand, x + 10, y + 1, z + 9, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 1, z + 9, Blocks.air, 0, 3);
		setBlock(world, rand, x + 12, y + 1, z + 9, Blocks.air, 0, 3);
		setBlock(world, rand, x + 14, y + 1, z + 9, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + 1, z + 9, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 16, y + 1, z + 9, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 1, z + 9, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 1, z + 9, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 1, z + 10, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 1, z + 10, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + 1, z + 10, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 6, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 8, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 10, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 12, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + 1, z + 10, Blocks.air, 0, 3);
		setBlock(world, rand, x + 14, y + 1, z + 10, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 16, y + 1, z + 10, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 1, z + 10, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 1, z + 10, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 1, z + 11, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 1, z + 11, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 1, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + 1, z + 11, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 4, y + 1, z + 11, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + 1, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 6, y + 1, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 1, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 8, y + 1, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 1, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 10, y + 1, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 1, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 12, y + 1, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + 1, z + 11, Blocks.air, 0, 3);
		setBlock(world, rand, x + 14, y + 1, z + 11, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + 1, z + 11, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 16, y + 1, z + 11, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 1, z + 11, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 1, z + 11, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 1, z + 12, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 1, z + 12, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 1, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + 1, z + 12, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + 1, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 6, y + 1, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 1, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 8, y + 1, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 1, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 10, y + 1, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 1, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 12, y + 1, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + 1, z + 12, Blocks.air, 0, 3);
		setBlock(world, rand, x + 14, y + 1, z + 12, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 16, y + 1, z + 12, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 1, z + 12, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 1, z + 12, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 1, z + 13, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 1, z + 13, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 1, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + 1, z + 13, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 4, y + 1, z + 13, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + 1, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 6, y + 1, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 1, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 1, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 1, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 12, y + 1, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + 1, z + 13, Blocks.air, 0, 3);
		setBlock(world, rand, x + 14, y + 1, z + 13, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + 1, z + 13, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 16, y + 1, z + 13, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 1, z + 13, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 1, z + 13, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 1, z + 14, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 1, z + 14, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 1, z + 14, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + 1, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + 1, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 6, y + 1, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 7, y + 1, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 8, y + 1, z + 14, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 9, y + 1, z + 14, Blocks.wooden_door, 8, 3);
		setBlock(world, rand, x + 10, y + 1, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 11, y + 1, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 12, y + 1, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 13, y + 1, z + 14, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 14, y + 1, z + 14, Blocks.cobblestone, 0, 3);
//		setBlock(world, rand, x + 16, y + 1, z + 14, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 1, z + 14, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 1, z + 14, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 1, z + 15, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 1, z + 15, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 1, z + 15, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + 1, z + 15, Blocks.air, 0, 3);
		setBlock(world, rand, x + 5, y + 1, z + 15, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 7, y + 1, z + 15, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 9, y + 1, z + 15, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 1, z + 15, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 13, y + 1, z + 15, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + 1, z + 15, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + 1, z + 15, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 1, z + 15, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 1, z + 15, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + 1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 4, y + 1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 5, y + 1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 6, y + 1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 7, y + 1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 8, y + 1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 9, y + 1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 10, y + 1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 11, y + 1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 12, y + 1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 13, y + 1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 14, y + 1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 15, y + 1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + 1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 1, z + 16, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + 1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 4, y + 1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 5, y + 1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 6, y + 1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 7, y + 1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 8, y + 1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 9, y + 1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 10, y + 1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 11, y + 1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 12, y + 1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 13, y + 1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 14, y + 1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 15, y + 1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + 1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 1, z + 17, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 0, y + 1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 1, y + 1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 2, y + 1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 3, y + 1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 4, y + 1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 5, y + 1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 6, y + 1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 7, y + 1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 8, y + 1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 9, y + 1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 10, y + 1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 11, y + 1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 12, y + 1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 13, y + 1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 14, y + 1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 15, y + 1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 16, y + 1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 17, y + 1, z + 18, Blocks.air, 0, 3);
//		setBlock(world, rand, x + 18, y + 1, z + 18, Blocks.air, 0, 3);

		setBlock(world, rand, x + 0, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, rand, x + 1, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, rand, x + 2, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, rand, x + 5, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, rand, x + 6, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, rand, x + 8, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, rand, x + 10, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, rand, x + 12, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, rand, x + 14, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, rand, x + 15, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, rand, x + 16, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, rand, x + 17, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, rand, x + 18, y + 2, z + 0, Blocks.air, 0, 3);
		setBlock(world, rand, x + 0, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, rand, x + 1, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, rand, x + 2, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, rand, x + 5, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, rand, x + 6, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, rand, x + 8, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, rand, x + 10, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, rand, x + 12, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, rand, x + 14, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, rand, x + 15, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, rand, x + 16, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, rand, x + 17, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, rand, x + 18, y + 2, z + 1, Blocks.air, 0, 3);
		setBlock(world, rand, x + 0, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, rand, x + 1, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, rand, x + 2, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, rand, x + 5, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, rand, x + 6, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, rand, x + 8, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, rand, x + 10, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, rand, x + 12, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, rand, x + 14, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, rand, x + 15, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, rand, x + 16, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, rand, x + 17, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, rand, x + 18, y + 2, z + 2, Blocks.air, 0, 3);
		setBlock(world, rand, x + 0, y + 2, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 1, y + 2, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 2, y + 2, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + 2, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + 2, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 5, y + 2, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 6, y + 2, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 2, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 8, y + 2, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 2, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 10, y + 2, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 2, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 12, y + 2, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + 2, z + 3, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 14, y + 2, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 15, y + 2, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 16, y + 2, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 17, y + 2, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 18, y + 2, z + 3, Blocks.air, 0, 3);
		setBlock(world, rand, x + 0, y + 2, z + 4, Blocks.air, 0, 3);
		setBlock(world, rand, x + 1, y + 2, z + 4, Blocks.air, 0, 3);
		setBlock(world, rand, x + 2, y + 2, z + 4, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + 2, z + 4, Blocks.air, 0, 3);
		setBlock(world, rand, x + 4, y + 2, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + 2, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 6, y + 2, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 7, y + 2, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 8, y + 2, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 9, y + 2, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 10, y + 2, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 11, y + 2, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 12, y + 2, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 13, y + 2, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 14, y + 2, z + 4, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + 2, z + 4, Blocks.air, 0, 3);
		setBlock(world, rand, x + 16, y + 2, z + 4, Blocks.air, 0, 3);
		setBlock(world, rand, x + 17, y + 2, z + 4, Blocks.air, 0, 3);
		setBlock(world, rand, x + 18, y + 2, z + 4, Blocks.air, 0, 3);
		setBlock(world, rand, x + 0, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 1, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 2, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 3, y + 2, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 4, y + 2, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 5, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 6, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 7, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 8, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 9, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 10, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 11, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 12, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 13, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 14, y + 2, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 15, y + 2, z + 5, Blocks.cobblestone, 0, 3);
		setBlock(world, rand, x + 16, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 17, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 18, y + 2, z + 5, Blocks.air, 0, 3);
		setBlock(world, rand, x + 0, y + 2, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 1, y + 2, z + 6, Blocks.air, 0, 3);
		setBlock(world, rand, x + 2, y + 2, z + 6, Blocks.air, 0, 3);

		LogHelper.info("First part of Skyrim Style House done at: " + x + "," + y + "," + z + "!");

		preventLag();

		running = false; // Half built, let another thread start now
		
		new SkyrimStyleHouse1().generateStructure1(world, rand, x, y, z);
	}
}