package com.thexfactor117.ascension.structures;

import java.util.Random;

import com.thexfactor117.ascension.help.LogHelper;
import com.thexfactor117.ascension.help.Reference;
import com.thexfactor117.ascension.structures.StructureCoordinates.Structures;

import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.world.World;

/**
 * 
 * @author WILLIAM
 *
 */
public class Sphinx_000 extends AbandonedStructure {
	// Variables for configuration
	public static int missingBlockChance = 1;    // 1/n chance of setting block, set not less than 1, to 1 to set all blocks
	public static int spawnHeightTolerance = 3;   // Set larger for bigger structures
	public static int spawnChance = Reference.spawnChanceSphinx;  // chance n/100
	private static int doorX = 10;
//	private static int doorZ = 34;
	private static int doorZ = 0;
	private static int xMax = 20;
	private static int zMax = 34;
    
	public Sphinx_000() 
	{
		super(missingBlockChance, spawnHeightTolerance, spawnChance, Structures.SPHINX, 
				getValidSpawnBlocks(), getMobsToSpawn(), doorX, doorZ, xMax, zMax);
		baseBlock = Blocks.sand;

		int i = 0;
		addItemsForAllChests(i);		
	}

	protected static String[] getMobsToSpawn() {
		return new String[] { "Ghost", "Barbarian", "Valkyrie" };
	}
	
	protected static Block[] getValidSpawnBlocks() 
	{
		return new Block[] { Blocks.sand, Blocks.sandstone };
	}

	@Override
	// Upper level (above ground), from SphinxUpperRoom.schematic
	// 21 wide (x) x 35 length (z) x 6 height (y)
	public boolean generate(World world, Random random, int x, int y,	int z) {
		floorLevel = y;

		LogHelper.info("Generating Sphinx at " + x + "," + y + "," + z + "!");

		preventLag();

		// Build upper part first, because sand can fall down if undermined!
		
		// Head of statue, from SphinxHead.schematic
		// 11 wide (x) x 11 length (z) x 8 height (y)
		new SphinxHead_000().generate_r00(world, random, x + 5, y + 11, z + 10);

		// Lower part of statue, from SphinxStatue.schematic
		// 13 wide (x) x 24 length (z) x 5 height (y)
		new SphinxStatue_000().generate_r00(world, random, x + 4, y + 6, z + 8);

		new Sphinx_001().generate_r00(world, random, x, y, z);

		world.setBlock(x + 0, y + 1, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 1, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 2, y + 1, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 1, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 1, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 1, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 1, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 1, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 1, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 1, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 1, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 1, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 1, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 13, y + 1, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 14, y + 1, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 15, y + 1, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 16, y + 1, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 17, y + 1, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 18, y + 1, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 19, y + 1, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 1, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 0, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 2, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 1, z + 1, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 1, z + 1, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 13, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 14, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 15, y + 1, z + 1, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 1, z + 1, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 18, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 19, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 0, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 2, y + 1, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 3, y + 1, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 1, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 1, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 1, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 1, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 13, y + 1, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 14, y + 1, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 15, y + 1, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 1, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 1, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 18, y + 1, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 19, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 0, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 1, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 2, y + 1, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 3, y + 1, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 1, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 1, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 1, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 1, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 1, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 1, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 1, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 1, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 1, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 13, y + 1, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 14, y + 1, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 15, y + 1, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 1, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 1, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 18, y + 1, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 19, y + 1, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 20, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 0, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 1, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 2, y + 1, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 3, y + 1, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 1, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 1, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 1, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 1, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 1, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 1, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 1, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 1, z + 4, Blocks.sandstone, 2, 3);

		preventLag();

		world.setBlock(x + 12, y + 1, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 13, y + 1, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 14, y + 1, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 15, y + 1, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 1, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 1, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 18, y + 1, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 19, y + 1, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 20, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 0, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 1, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 2, y + 1, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 3, y + 1, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 1, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 1, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 1, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 1, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 1, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 1, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 1, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 1, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 1, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 13, y + 1, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 14, y + 1, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 15, y + 1, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 1, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 1, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 18, y + 1, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 19, y + 1, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 20, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 0, y + 1, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 1, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 2, y + 1, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 3, y + 1, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 1, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 1, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 1, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 1, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 1, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 1, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 1, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 1, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 1, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 13, y + 1, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 14, y + 1, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 15, y + 1, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 1, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 1, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 18, y + 1, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 19, y + 1, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 20, y + 1, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 0, y + 1, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 1, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 2, y + 1, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 3, y + 1, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 1, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 1, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 1, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 1, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 1, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 1, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 1, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 1, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 1, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 13, y + 1, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 14, y + 1, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 15, y + 1, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 1, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 1, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 18, y + 1, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 19, y + 1, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 20, y + 1, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 0, y + 1, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 1, z + 8, Blocks.sandstone, 2, 3);
		world.setBlock(x + 2, y + 1, z + 8, Blocks.sandstone, 2, 3);
		world.setBlock(x + 3, y + 1, z + 8, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 1, z + 8, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 1, z + 8, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 1, z + 8, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 1, z + 8, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 1, z + 8, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 1, z + 8, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 1, z + 8, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 1, z + 8, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 1, z + 8, Blocks.sandstone, 2, 3);
		world.setBlock(x + 13, y + 1, z + 8, Blocks.sandstone, 2, 3);
		world.setBlock(x + 14, y + 1, z + 8, Blocks.sandstone, 2, 3);
		world.setBlock(x + 15, y + 1, z + 8, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 1, z + 8, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 1, z + 8, Blocks.sandstone, 2, 3);
		world.setBlock(x + 18, y + 1, z + 8, Blocks.sandstone, 2, 3);
		world.setBlock(x + 19, y + 1, z + 8, Blocks.sandstone, 2, 3);
		world.setBlock(x + 20, y + 1, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 0, y + 1, z + 9, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 1, z + 9, Blocks.sandstone, 2, 3);
		world.setBlock(x + 2, y + 1, z + 9, Blocks.sandstone, 2, 3);
		world.setBlock(x + 3, y + 1, z + 9, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 1, z + 9, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 1, z + 9, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 1, z + 9, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 1, z + 9, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 1, z + 9, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 1, z + 9, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 1, z + 9, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 1, z + 9, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 1, z + 9, Blocks.sandstone, 2, 3);
		world.setBlock(x + 13, y + 1, z + 9, Blocks.sandstone, 2, 3);
		world.setBlock(x + 14, y + 1, z + 9, Blocks.sandstone, 2, 3);
		world.setBlock(x + 15, y + 1, z + 9, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 1, z + 9, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 1, z + 9, Blocks.sandstone, 2, 3);
		world.setBlock(x + 18, y + 1, z + 9, Blocks.sandstone, 2, 3);
		world.setBlock(x + 19, y + 1, z + 9, Blocks.sandstone, 2, 3);
		world.setBlock(x + 20, y + 1, z + 9, Blocks.air, 0, 3);
		world.setBlock(x + 0, y + 1, z + 10, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 1, z + 10, Blocks.sandstone, 2, 3);
		world.setBlock(x + 2, y + 1, z + 10, Blocks.sandstone, 2, 3);
		world.setBlock(x + 3, y + 1, z + 10, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 1, z + 10, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 1, z + 10, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 1, z + 10, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 1, z + 10, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 1, z + 10, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 1, z + 10, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 1, z + 10, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 1, z + 10, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 1, z + 10, Blocks.sandstone, 2, 3);
		world.setBlock(x + 13, y + 1, z + 10, Blocks.sandstone, 2, 3);
		world.setBlock(x + 14, y + 1, z + 10, Blocks.sandstone, 2, 3);
		world.setBlock(x + 15, y + 1, z + 10, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 1, z + 10, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 1, z + 10, Blocks.sandstone, 2, 3);
		world.setBlock(x + 18, y + 1, z + 10, Blocks.sandstone, 2, 3);
		world.setBlock(x + 19, y + 1, z + 10, Blocks.sandstone, 2, 3);
		world.setBlock(x + 20, y + 1, z + 10, Blocks.air, 0, 3);
		world.setBlock(x + 0, y + 1, z + 11, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 1, z + 11, Blocks.sandstone, 2, 3);
		world.setBlock(x + 2, y + 1, z + 11, Blocks.sandstone, 2, 3);
		world.setBlock(x + 3, y + 1, z + 11, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 1, z + 11, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 1, z + 11, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 1, z + 11, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 1, z + 11, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 1, z + 11, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 1, z + 11, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 1, z + 11, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 1, z + 11, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 1, z + 11, Blocks.sandstone, 2, 3);
		world.setBlock(x + 13, y + 1, z + 11, Blocks.sandstone, 2, 3);
		world.setBlock(x + 14, y + 1, z + 11, Blocks.sandstone, 2, 3);
		world.setBlock(x + 15, y + 1, z + 11, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 1, z + 11, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 1, z + 11, Blocks.sandstone, 2, 3);
		world.setBlock(x + 18, y + 1, z + 11, Blocks.sandstone, 2, 3);
		world.setBlock(x + 19, y + 1, z + 11, Blocks.sandstone, 2, 3);

		preventLag();

		world.setBlock(x + 20, y + 1, z + 11, Blocks.air, 0, 3);
		world.setBlock(x + 0, y + 1, z + 12, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 1, z + 12, Blocks.sandstone, 2, 3);
		world.setBlock(x + 2, y + 1, z + 12, Blocks.sandstone, 2, 3);
		world.setBlock(x + 3, y + 1, z + 12, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 1, z + 12, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 1, z + 12, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 1, z + 12, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 1, z + 12, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 1, z + 12, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 1, z + 12, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 1, z + 12, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 1, z + 12, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 1, z + 12, Blocks.sandstone, 2, 3);
		world.setBlock(x + 13, y + 1, z + 12, Blocks.sandstone, 2, 3);
		world.setBlock(x + 14, y + 1, z + 12, Blocks.sandstone, 2, 3);
		world.setBlock(x + 15, y + 1, z + 12, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 1, z + 12, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 1, z + 12, Blocks.sandstone, 2, 3);
		world.setBlock(x + 18, y + 1, z + 12, Blocks.sandstone, 2, 3);
		world.setBlock(x + 19, y + 1, z + 12, Blocks.sandstone, 2, 3);
		world.setBlock(x + 20, y + 1, z + 12, Blocks.air, 0, 3);
		world.setBlock(x + 0, y + 1, z + 13, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 1, z + 13, Blocks.sandstone, 2, 3);
		world.setBlock(x + 2, y + 1, z + 13, Blocks.sandstone, 2, 3);
		world.setBlock(x + 3, y + 1, z + 13, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 1, z + 13, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 1, z + 13, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 1, z + 13, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 1, z + 13, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 1, z + 13, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 1, z + 13, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 1, z + 13, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 1, z + 13, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 1, z + 13, Blocks.sandstone, 2, 3);
		world.setBlock(x + 13, y + 1, z + 13, Blocks.sandstone, 2, 3);
		world.setBlock(x + 14, y + 1, z + 13, Blocks.sandstone, 2, 3);
		world.setBlock(x + 15, y + 1, z + 13, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 1, z + 13, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 1, z + 13, Blocks.sandstone, 2, 3);
		world.setBlock(x + 18, y + 1, z + 13, Blocks.sandstone, 2, 3);
		world.setBlock(x + 19, y + 1, z + 13, Blocks.sandstone, 2, 3);
		world.setBlock(x + 20, y + 1, z + 13, Blocks.air, 0, 3);
		world.setBlock(x + 0, y + 1, z + 14, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 1, z + 14, Blocks.air, 0, 3);
		world.setBlock(x + 2, y + 1, z + 14, Blocks.sandstone, 2, 3);
		world.setBlock(x + 3, y + 1, z + 14, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 1, z + 14, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 1, z + 14, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 1, z + 14, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 1, z + 14, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 1, z + 14, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 1, z + 14, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 1, z + 14, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 1, z + 14, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 1, z + 14, Blocks.sandstone, 2, 3);
		world.setBlock(x + 13, y + 1, z + 14, Blocks.sandstone, 2, 3);
		world.setBlock(x + 14, y + 1, z + 14, Blocks.sandstone, 2, 3);
		world.setBlock(x + 15, y + 1, z + 14, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 1, z + 14, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 1, z + 14, Blocks.sandstone, 2, 3);
		world.setBlock(x + 18, y + 1, z + 14, Blocks.sandstone, 2, 3);
		world.setBlock(x + 19, y + 1, z + 14, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 1, z + 14, Blocks.air, 0, 3);
		world.setBlock(x + 0, y + 1, z + 15, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 1, z + 15, Blocks.air, 0, 3);
		world.setBlock(x + 2, y + 1, z + 15, Blocks.sandstone, 2, 3);
		world.setBlock(x + 3, y + 1, z + 15, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 1, z + 15, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 1, z + 15, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 1, z + 15, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 1, z + 15, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 1, z + 15, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 1, z + 15, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 1, z + 15, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 1, z + 15, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 1, z + 15, Blocks.sandstone, 2, 3);
		world.setBlock(x + 13, y + 1, z + 15, Blocks.sandstone, 2, 3);
		world.setBlock(x + 14, y + 1, z + 15, Blocks.sandstone, 2, 3);
		world.setBlock(x + 15, y + 1, z + 15, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 1, z + 15, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 1, z + 15, Blocks.sandstone, 2, 3);
		world.setBlock(x + 18, y + 1, z + 15, Blocks.sandstone, 2, 3);
		world.setBlock(x + 19, y + 1, z + 15, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 1, z + 15, Blocks.air, 0, 3);
		world.setBlock(x + 0, y + 1, z + 16, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 1, z + 16, Blocks.air, 0, 3);
		world.setBlock(x + 2, y + 1, z + 16, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 1, z + 16, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 1, z + 16, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 1, z + 16, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 1, z + 16, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 1, z + 16, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 1, z + 16, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 1, z + 16, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 1, z + 16, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 1, z + 16, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 1, z + 16, Blocks.sandstone, 2, 3);
		world.setBlock(x + 13, y + 1, z + 16, Blocks.sandstone, 2, 3);
		world.setBlock(x + 14, y + 1, z + 16, Blocks.sandstone, 2, 3);
		world.setBlock(x + 15, y + 1, z + 16, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 1, z + 16, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 1, z + 16, Blocks.sandstone, 2, 3);
		world.setBlock(x + 18, y + 1, z + 16, Blocks.air, 0, 3);
		world.setBlock(x + 19, y + 1, z + 16, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 1, z + 16, Blocks.air, 0, 3);
		world.setBlock(x + 0, y + 1, z + 17, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 1, z + 17, Blocks.air, 0, 3);
		world.setBlock(x + 2, y + 1, z + 17, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 1, z + 17, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 1, z + 17, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 1, z + 17, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 1, z + 17, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 1, z + 17, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 1, z + 17, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 1, z + 17, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 1, z + 17, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 1, z + 17, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 1, z + 17, Blocks.sandstone, 2, 3);
		world.setBlock(x + 13, y + 1, z + 17, Blocks.sandstone, 2, 3);
		world.setBlock(x + 14, y + 1, z + 17, Blocks.sandstone, 2, 3);
		world.setBlock(x + 15, y + 1, z + 17, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 1, z + 17, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 1, z + 17, Blocks.sandstone, 2, 3);
		world.setBlock(x + 18, y + 1, z + 17, Blocks.air, 0, 3);
		world.setBlock(x + 19, y + 1, z + 17, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 1, z + 17, Blocks.air, 0, 3);
		world.setBlock(x + 0, y + 1, z + 18, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 1, z + 18, Blocks.air, 0, 3);
		world.setBlock(x + 2, y + 1, z + 18, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 1, z + 18, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 1, z + 18, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 1, z + 18, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 1, z + 18, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 1, z + 18, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 1, z + 18, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 1, z + 18, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 1, z + 18, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 1, z + 18, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 1, z + 18, Blocks.sandstone, 2, 3);
		world.setBlock(x + 13, y + 1, z + 18, Blocks.sandstone, 2, 3);
		world.setBlock(x + 14, y + 1, z + 18, Blocks.sandstone, 2, 3);
		world.setBlock(x + 15, y + 1, z + 18, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 1, z + 18, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 1, z + 18, Blocks.sandstone, 2, 3);
		world.setBlock(x + 18, y + 1, z + 18, Blocks.air, 0, 3);
		world.setBlock(x + 19, y + 1, z + 18, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 1, z + 18, Blocks.air, 0, 3);
		world.setBlock(x + 0, y + 1, z + 19, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 1, z + 19, Blocks.air, 0, 3);
		world.setBlock(x + 2, y + 1, z + 19, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 1, z + 19, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 1, z + 19, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 1, z + 19, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 1, z + 19, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 1, z + 19, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 1, z + 19, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 1, z + 19, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 1, z + 19, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 1, z + 19, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 1, z + 19, Blocks.sandstone, 2, 3);
		world.setBlock(x + 13, y + 1, z + 19, Blocks.sandstone, 2, 3);
		world.setBlock(x + 14, y + 1, z + 19, Blocks.sandstone, 2, 3);
		world.setBlock(x + 15, y + 1, z + 19, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 1, z + 19, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 1, z + 19, Blocks.sandstone, 2, 3);
		world.setBlock(x + 18, y + 1, z + 19, Blocks.air, 0, 3);
		world.setBlock(x + 19, y + 1, z + 19, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 1, z + 19, Blocks.air, 0, 3);
		world.setBlock(x + 0, y + 1, z + 20, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 1, z + 20, Blocks.air, 0, 3);
		world.setBlock(x + 2, y + 1, z + 20, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 1, z + 20, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 1, z + 20, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 1, z + 20, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 1, z + 20, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 1, z + 20, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 1, z + 20, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 1, z + 20, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 1, z + 20, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 1, z + 20, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 1, z + 20, Blocks.sandstone, 2, 3);
		world.setBlock(x + 13, y + 1, z + 20, Blocks.sandstone, 2, 3);
		world.setBlock(x + 14, y + 1, z + 20, Blocks.sandstone, 2, 3);
		world.setBlock(x + 15, y + 1, z + 20, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 1, z + 20, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 1, z + 20, Blocks.sandstone, 2, 3);
		world.setBlock(x + 18, y + 1, z + 20, Blocks.air, 0, 3);
		world.setBlock(x + 19, y + 1, z + 20, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 1, z + 20, Blocks.air, 0, 3);
		world.setBlock(x + 0, y + 1, z + 21, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 1, z + 21, Blocks.air, 0, 3);
		world.setBlock(x + 2, y + 1, z + 21, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 1, z + 21, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 1, z + 21, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 1, z + 21, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 1, z + 21, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 1, z + 21, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 8, y + 1, z + 21, Blocks.mob_spawner, 0, 3);
		world.setBlock(x + 9, y + 1, z + 21, Blocks.stone_brick_stairs, 3, 3);
		world.setBlock(x + 10, y + 1, z + 21, Blocks.stone_brick_stairs, 3, 3);
		world.setBlock(x + 11, y + 1, z + 21, Blocks.stone_brick_stairs, 3, 3);
//		world.setBlock(x + 12, y + 1, z + 21, Blocks.mob_spawner, 0, 3);
		world.setBlock(x + 13, y + 1, z + 21, Blocks.sandstone, 2, 3);
		world.setBlock(x + 14, y + 1, z + 21, Blocks.sandstone, 2, 3);
		world.setBlock(x + 15, y + 1, z + 21, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 1, z + 21, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 1, z + 21, Blocks.air, 0, 3);
		world.setBlock(x + 18, y + 1, z + 21, Blocks.air, 0, 3);
		world.setBlock(x + 19, y + 1, z + 21, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 1, z + 21, Blocks.air, 0, 3);
		world.setBlock(x + 0, y + 1, z + 22, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 1, z + 22, Blocks.air, 0, 3);
		world.setBlock(x + 2, y + 1, z + 22, Blocks.air, 0, 3);

		// corner
//		world.setBlock(x + 0, y + 0, z + 0, Blocks.air, 0, 3);
//		world.setBlock(x + 1, y + 0, z + 0, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 0, z + 0, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 0, z + 0, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 0, z + 0, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 0, z + 0, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 7, y + 0, z + 0, Blocks.air, 0, 3);
//		world.setBlock(x + 8, y + 0, z + 0, Blocks.air, 0, 3);
//		world.setBlock(x + 9, y + 0, z + 0, Blocks.air, 0, 3);
//		world.setBlock(x + 10, y + 0, z + 0, Blocks.air, 0, 3);
//		world.setBlock(x + 11, y + 0, z + 0, Blocks.air, 0, 3);
//		world.setBlock(x + 12, y + 0, z + 0, Blocks.air, 0, 3);
//		world.setBlock(x + 13, y + 0, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 14, y + 0, z + 0, Blocks.sandstone, 2, 3);
		world.setBlock(x + 15, y + 0, z + 0, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 0, z + 0, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 0, z + 0, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 18, y + 0, z + 0, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 0, Blocks.air, 0, 3);
//		world.setBlock(x + 20, y + 0, z + 0, Blocks.air, 0, 3);
//		world.setBlock(x + 0, y + 0, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 0, z + 1, Blocks.sandstone, 2, 3);
		world.setBlock(x + 2, y + 0, z + 1, Blocks.sandstone, 2, 3);
		world.setBlock(x + 3, y + 0, z + 1, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 4, y + 0, z + 1, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 0, z + 1, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 0, z + 1, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 0, z + 1, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 9, y + 0, z + 1, Blocks.air, 0, 3);
//		world.setBlock(x + 10, y + 0, z + 1, Blocks.air, 0, 3);
//		world.setBlock(x + 11, y + 0, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 0, z + 1, Blocks.sandstone, 2, 3);
		world.setBlock(x + 13, y + 0, z + 1, Blocks.sandstone, 2, 3);
		world.setBlock(x + 14, y + 0, z + 1, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 15, y + 0, z + 1, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 17, y + 0, z + 1, Blocks.sandstone, 2, 3);
		world.setBlock(x + 18, y + 0, z + 1, Blocks.sandstone, 2, 3);
		world.setBlock(x + 19, y + 0, z + 1, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 20, y + 0, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 0, y + 0, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 1, y + 0, z + 2, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 2, y + 0, z + 2, Blocks.air, 0, 3);
//		world.setBlock(x + 3, y + 0, z + 2, Blocks.air, 0, 3);
//		world.setBlock(x + 4, y + 0, z + 2, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 2, Blocks.air, 0, 3);
//		world.setBlock(x + 6, y + 0, z + 2, Blocks.air, 0, 3);
//		world.setBlock(x + 7, y + 0, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 0, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 0, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 0, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 0, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 0, z + 2, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 13, y + 0, z + 2, Blocks.air, 0, 3);
//		world.setBlock(x + 14, y + 0, z + 2, Blocks.air, 0, 3);
//		world.setBlock(x + 15, y + 0, z + 2, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 2, Blocks.air, 0, 3);
//		world.setBlock(x + 17, y + 0, z + 2, Blocks.air, 0, 3);
//		world.setBlock(x + 18, y + 0, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 19, y + 0, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 20, y + 0, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 0, y + 0, z + 3, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 1, y + 0, z + 3, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 3, Blocks.air, 0, 3);
//		world.setBlock(x + 3, y + 0, z + 3, Blocks.air, 0, 3);
//		world.setBlock(x + 4, y + 0, z + 3, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 3, Blocks.air, 0, 3);
//		world.setBlock(x + 6, y + 0, z + 3, Blocks.air, 0, 3);
//		world.setBlock(x + 7, y + 0, z + 3, Blocks.air, 0, 3);
//		world.setBlock(x + 8, y + 0, z + 3, Blocks.air, 0, 3);
//		world.setBlock(x + 9, y + 0, z + 3, Blocks.air, 0, 3);
//		world.setBlock(x + 10, y + 0, z + 3, Blocks.air, 0, 3);
//		world.setBlock(x + 11, y + 0, z + 3, Blocks.air, 0, 3);
//		world.setBlock(x + 12, y + 0, z + 3, Blocks.air, 0, 3);
//		world.setBlock(x + 13, y + 0, z + 3, Blocks.air, 0, 3);
//		world.setBlock(x + 14, y + 0, z + 3, Blocks.air, 0, 3);
//		world.setBlock(x + 15, y + 0, z + 3, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 3, Blocks.air, 0, 3);
//		world.setBlock(x + 17, y + 0, z + 3, Blocks.air, 0, 3);
//		world.setBlock(x + 18, y + 0, z + 3, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 0, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 0, y + 0, z + 4, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 1, y + 0, z + 4, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 4, Blocks.air, 0, 3);
//		world.setBlock(x + 3, y + 0, z + 4, Blocks.air, 0, 3);
//		world.setBlock(x + 4, y + 0, z + 4, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 4, Blocks.air, 0, 3);
//		world.setBlock(x + 6, y + 0, z + 4, Blocks.air, 0, 3);
//		world.setBlock(x + 7, y + 0, z + 4, Blocks.air, 0, 3);
//		world.setBlock(x + 8, y + 0, z + 4, Blocks.air, 0, 3);
//		world.setBlock(x + 9, y + 0, z + 4, Blocks.air, 0, 3);
//		world.setBlock(x + 10, y + 0, z + 4, Blocks.air, 0, 3);
//		world.setBlock(x + 11, y + 0, z + 4, Blocks.air, 0, 3);
//		world.setBlock(x + 12, y + 0, z + 4, Blocks.air, 0, 3);
//		world.setBlock(x + 13, y + 0, z + 4, Blocks.air, 0, 3);
//		world.setBlock(x + 14, y + 0, z + 4, Blocks.air, 0, 3);
//		world.setBlock(x + 15, y + 0, z + 4, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 4, Blocks.air, 0, 3);
//		world.setBlock(x + 17, y + 0, z + 4, Blocks.air, 0, 3);
//		world.setBlock(x + 18, y + 0, z + 4, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 0, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 0, y + 0, z + 5, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 1, y + 0, z + 5, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 5, Blocks.air, 0, 3);
//		world.setBlock(x + 3, y + 0, z + 5, Blocks.air, 0, 3);
//		world.setBlock(x + 4, y + 0, z + 5, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 5, Blocks.air, 0, 3);
//		world.setBlock(x + 6, y + 0, z + 5, Blocks.air, 0, 3);
//		world.setBlock(x + 7, y + 0, z + 5, Blocks.air, 0, 3);
//		world.setBlock(x + 8, y + 0, z + 5, Blocks.air, 0, 3);
//		world.setBlock(x + 9, y + 0, z + 5, Blocks.air, 0, 3);
//		world.setBlock(x + 10, y + 0, z + 5, Blocks.air, 0, 3);
//		world.setBlock(x + 11, y + 0, z + 5, Blocks.air, 0, 3);
//		world.setBlock(x + 12, y + 0, z + 5, Blocks.air, 0, 3);
//		world.setBlock(x + 13, y + 0, z + 5, Blocks.air, 0, 3);
//		world.setBlock(x + 14, y + 0, z + 5, Blocks.air, 0, 3);
//		world.setBlock(x + 15, y + 0, z + 5, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 5, Blocks.air, 0, 3);
//		world.setBlock(x + 17, y + 0, z + 5, Blocks.air, 0, 3);
//		world.setBlock(x + 18, y + 0, z + 5, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 0, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 0, y + 0, z + 6, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 1, y + 0, z + 6, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 6, Blocks.air, 0, 3);
//		world.setBlock(x + 3, y + 0, z + 6, Blocks.air, 0, 3);
//		world.setBlock(x + 4, y + 0, z + 6, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 6, Blocks.air, 0, 3);
//		world.setBlock(x + 6, y + 0, z + 6, Blocks.air, 0, 3);
//		world.setBlock(x + 7, y + 0, z + 6, Blocks.air, 0, 3);
//		world.setBlock(x + 8, y + 0, z + 6, Blocks.air, 0, 3);
//		world.setBlock(x + 9, y + 0, z + 6, Blocks.air, 0, 3);
//		world.setBlock(x + 10, y + 0, z + 6, Blocks.air, 0, 3);
//		world.setBlock(x + 11, y + 0, z + 6, Blocks.air, 0, 3);
//		world.setBlock(x + 12, y + 0, z + 6, Blocks.air, 0, 3);
//		world.setBlock(x + 13, y + 0, z + 6, Blocks.air, 0, 3);
//		world.setBlock(x + 14, y + 0, z + 6, Blocks.air, 0, 3);
//		world.setBlock(x + 15, y + 0, z + 6, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 6, Blocks.air, 0, 3);
//		world.setBlock(x + 17, y + 0, z + 6, Blocks.air, 0, 3);
//		world.setBlock(x + 18, y + 0, z + 6, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 0, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 0, y + 0, z + 7, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 1, y + 0, z + 7, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 7, Blocks.air, 0, 3);
//		world.setBlock(x + 3, y + 0, z + 7, Blocks.air, 0, 3);
//		world.setBlock(x + 4, y + 0, z + 7, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 7, Blocks.air, 0, 3);
//		world.setBlock(x + 6, y + 0, z + 7, Blocks.air, 0, 3);
//		world.setBlock(x + 7, y + 0, z + 7, Blocks.air, 0, 3);
//		world.setBlock(x + 8, y + 0, z + 7, Blocks.air, 0, 3);
//		world.setBlock(x + 9, y + 0, z + 7, Blocks.air, 0, 3);
//		world.setBlock(x + 10, y + 0, z + 7, Blocks.air, 0, 3);
//		world.setBlock(x + 11, y + 0, z + 7, Blocks.air, 0, 3);
//		world.setBlock(x + 12, y + 0, z + 7, Blocks.air, 0, 3);
//		world.setBlock(x + 13, y + 0, z + 7, Blocks.air, 0, 3);
//		world.setBlock(x + 14, y + 0, z + 7, Blocks.air, 0, 3);
//		world.setBlock(x + 15, y + 0, z + 7, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 7, Blocks.air, 0, 3);
//		world.setBlock(x + 17, y + 0, z + 7, Blocks.air, 0, 3);
//		world.setBlock(x + 18, y + 0, z + 7, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 0, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 0, y + 0, z + 8, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 1, y + 0, z + 8, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 8, Blocks.air, 0, 3);
//		world.setBlock(x + 3, y + 0, z + 8, Blocks.air, 0, 3);
//		world.setBlock(x + 4, y + 0, z + 8, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 8, Blocks.air, 0, 3);
//		world.setBlock(x + 6, y + 0, z + 8, Blocks.air, 0, 3);
//		world.setBlock(x + 7, y + 0, z + 8, Blocks.air, 0, 3);
//		world.setBlock(x + 8, y + 0, z + 8, Blocks.air, 0, 3);
//		world.setBlock(x + 9, y + 0, z + 8, Blocks.air, 0, 3);
//		world.setBlock(x + 10, y + 0, z + 8, Blocks.air, 0, 3);
//		world.setBlock(x + 11, y + 0, z + 8, Blocks.air, 0, 3);
//		world.setBlock(x + 12, y + 0, z + 8, Blocks.air, 0, 3);
//		world.setBlock(x + 13, y + 0, z + 8, Blocks.air, 0, 3);
//		world.setBlock(x + 14, y + 0, z + 8, Blocks.air, 0, 3);
//		world.setBlock(x + 15, y + 0, z + 8, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 8, Blocks.air, 0, 3);
//		world.setBlock(x + 17, y + 0, z + 8, Blocks.air, 0, 3);
//		world.setBlock(x + 18, y + 0, z + 8, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 8, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 0, z + 8, Blocks.sandstone, 2, 3);
		world.setBlock(x + 0, y + 0, z + 9, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 1, y + 0, z + 9, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 9, Blocks.air, 0, 3);
//		world.setBlock(x + 3, y + 0, z + 9, Blocks.air, 0, 3);
//		world.setBlock(x + 4, y + 0, z + 9, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 9, Blocks.air, 0, 3);
//		world.setBlock(x + 6, y + 0, z + 9, Blocks.air, 0, 3);
//		world.setBlock(x + 7, y + 0, z + 9, Blocks.air, 0, 3);
//		world.setBlock(x + 8, y + 0, z + 9, Blocks.air, 0, 3);
//		world.setBlock(x + 9, y + 0, z + 9, Blocks.air, 0, 3);
//		world.setBlock(x + 10, y + 0, z + 9, Blocks.air, 0, 3);
//		world.setBlock(x + 11, y + 0, z + 9, Blocks.air, 0, 3);
//		world.setBlock(x + 12, y + 0, z + 9, Blocks.air, 0, 3);
//		world.setBlock(x + 13, y + 0, z + 9, Blocks.air, 0, 3);
//		world.setBlock(x + 14, y + 0, z + 9, Blocks.air, 0, 3);
//		world.setBlock(x + 15, y + 0, z + 9, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 9, Blocks.air, 0, 3);
//		world.setBlock(x + 17, y + 0, z + 9, Blocks.air, 0, 3);
//		world.setBlock(x + 18, y + 0, z + 9, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 9, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 0, z + 9, Blocks.sandstone, 2, 3);
		world.setBlock(x + 0, y + 0, z + 10, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 1, y + 0, z + 10, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 10, Blocks.air, 0, 3);
//		world.setBlock(x + 3, y + 0, z + 10, Blocks.air, 0, 3);
//		world.setBlock(x + 4, y + 0, z + 10, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 10, Blocks.air, 0, 3);
//		world.setBlock(x + 6, y + 0, z + 10, Blocks.air, 0, 3);
//		world.setBlock(x + 7, y + 0, z + 10, Blocks.air, 0, 3);
//		world.setBlock(x + 8, y + 0, z + 10, Blocks.air, 0, 3);
//		world.setBlock(x + 9, y + 0, z + 10, Blocks.air, 0, 3);
//		world.setBlock(x + 10, y + 0, z + 10, Blocks.air, 0, 3);
//		world.setBlock(x + 11, y + 0, z + 10, Blocks.air, 0, 3);
//		world.setBlock(x + 12, y + 0, z + 10, Blocks.air, 0, 3);
//		world.setBlock(x + 13, y + 0, z + 10, Blocks.air, 0, 3);
//		world.setBlock(x + 14, y + 0, z + 10, Blocks.air, 0, 3);
//		world.setBlock(x + 15, y + 0, z + 10, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 10, Blocks.air, 0, 3);
//		world.setBlock(x + 17, y + 0, z + 10, Blocks.air, 0, 3);
//		world.setBlock(x + 18, y + 0, z + 10, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 10, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 0, z + 10, Blocks.sandstone, 2, 3);
		world.setBlock(x + 0, y + 0, z + 11, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 1, y + 0, z + 11, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 11, Blocks.air, 0, 3);
//		world.setBlock(x + 3, y + 0, z + 11, Blocks.air, 0, 3);
//		world.setBlock(x + 4, y + 0, z + 11, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 11, Blocks.air, 0, 3);
//		world.setBlock(x + 6, y + 0, z + 11, Blocks.air, 0, 3);
//		world.setBlock(x + 7, y + 0, z + 11, Blocks.air, 0, 3);
//		world.setBlock(x + 8, y + 0, z + 11, Blocks.air, 0, 3);
//		world.setBlock(x + 9, y + 0, z + 11, Blocks.air, 0, 3);
//		world.setBlock(x + 10, y + 0, z + 11, Blocks.air, 0, 3);
//		world.setBlock(x + 11, y + 0, z + 11, Blocks.air, 0, 3);
//		world.setBlock(x + 12, y + 0, z + 11, Blocks.air, 0, 3);
//		world.setBlock(x + 13, y + 0, z + 11, Blocks.air, 0, 3);
//		world.setBlock(x + 14, y + 0, z + 11, Blocks.air, 0, 3);
//		world.setBlock(x + 15, y + 0, z + 11, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 11, Blocks.air, 0, 3);
//		world.setBlock(x + 17, y + 0, z + 11, Blocks.air, 0, 3);
//		world.setBlock(x + 18, y + 0, z + 11, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 11, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 0, z + 11, Blocks.sandstone, 2, 3);
		world.setBlock(x + 0, y + 0, z + 12, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 1, y + 0, z + 12, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 12, Blocks.air, 0, 3);
//		world.setBlock(x + 3, y + 0, z + 12, Blocks.air, 0, 3);
//		world.setBlock(x + 4, y + 0, z + 12, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 12, Blocks.air, 0, 3);
//		world.setBlock(x + 6, y + 0, z + 12, Blocks.air, 0, 3);
//		world.setBlock(x + 7, y + 0, z + 12, Blocks.air, 0, 3);
//		world.setBlock(x + 8, y + 0, z + 12, Blocks.air, 0, 3);
//		world.setBlock(x + 9, y + 0, z + 12, Blocks.air, 0, 3);
//		world.setBlock(x + 10, y + 0, z + 12, Blocks.air, 0, 3);
//		world.setBlock(x + 11, y + 0, z + 12, Blocks.air, 0, 3);
//		world.setBlock(x + 12, y + 0, z + 12, Blocks.air, 0, 3);
//		world.setBlock(x + 13, y + 0, z + 12, Blocks.air, 0, 3);
//		world.setBlock(x + 14, y + 0, z + 12, Blocks.air, 0, 3);
//		world.setBlock(x + 15, y + 0, z + 12, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 12, Blocks.air, 0, 3);
//		world.setBlock(x + 17, y + 0, z + 12, Blocks.air, 0, 3);
//		world.setBlock(x + 18, y + 0, z + 12, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 12, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 0, z + 12, Blocks.sandstone, 2, 3);
		world.setBlock(x + 0, y + 0, z + 13, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 1, y + 0, z + 13, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 13, Blocks.air, 0, 3);
//		world.setBlock(x + 3, y + 0, z + 13, Blocks.air, 0, 3);
//		world.setBlock(x + 4, y + 0, z + 13, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 13, Blocks.air, 0, 3);
//		world.setBlock(x + 6, y + 0, z + 13, Blocks.air, 0, 3);
//		world.setBlock(x + 7, y + 0, z + 13, Blocks.air, 0, 3);
//		world.setBlock(x + 8, y + 0, z + 13, Blocks.air, 0, 3);
//		world.setBlock(x + 9, y + 0, z + 13, Blocks.air, 0, 3);
//		world.setBlock(x + 10, y + 0, z + 13, Blocks.air, 0, 3);
//		world.setBlock(x + 11, y + 0, z + 13, Blocks.air, 0, 3);
//		world.setBlock(x + 12, y + 0, z + 13, Blocks.air, 0, 3);
//		world.setBlock(x + 13, y + 0, z + 13, Blocks.air, 0, 3);
//		world.setBlock(x + 14, y + 0, z + 13, Blocks.air, 0, 3);

		preventLag();

//		world.setBlock(x + 15, y + 0, z + 13, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 13, Blocks.air, 0, 3);
//		world.setBlock(x + 17, y + 0, z + 13, Blocks.air, 0, 3);
//		world.setBlock(x + 18, y + 0, z + 13, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 13, Blocks.air, 0, 3);
		world.setBlock(x + 20, y + 0, z + 13, Blocks.sandstone, 2, 3);
		world.setBlock(x + 0, y + 0, z + 14, Blocks.sandstone, 2, 3);
		world.setBlock(x + 1, y + 0, z + 14, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 2, y + 0, z + 14, Blocks.air, 0, 3);
//		world.setBlock(x + 3, y + 0, z + 14, Blocks.air, 0, 3);
//		world.setBlock(x + 4, y + 0, z + 14, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 14, Blocks.air, 0, 3);
//		world.setBlock(x + 6, y + 0, z + 14, Blocks.air, 0, 3);
//		world.setBlock(x + 7, y + 0, z + 14, Blocks.air, 0, 3);
//		world.setBlock(x + 8, y + 0, z + 14, Blocks.air, 0, 3);
//		world.setBlock(x + 9, y + 0, z + 14, Blocks.air, 0, 3);
//		world.setBlock(x + 10, y + 0, z + 14, Blocks.air, 0, 3);
//		world.setBlock(x + 11, y + 0, z + 14, Blocks.air, 0, 3);
//		world.setBlock(x + 12, y + 0, z + 14, Blocks.air, 0, 3);
//		world.setBlock(x + 13, y + 0, z + 14, Blocks.air, 0, 3);
//		world.setBlock(x + 14, y + 0, z + 14, Blocks.air, 0, 3);
//		world.setBlock(x + 15, y + 0, z + 14, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 14, Blocks.air, 0, 3);
//		world.setBlock(x + 17, y + 0, z + 14, Blocks.air, 0, 3);
//		world.setBlock(x + 18, y + 0, z + 14, Blocks.air, 0, 3);
		world.setBlock(x + 19, y + 0, z + 14, Blocks.sandstone, 2, 3);
		world.setBlock(x + 20, y + 0, z + 14, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 0, y + 0, z + 15, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 0, z + 15, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 2, y + 0, z + 15, Blocks.air, 0, 3);
//		world.setBlock(x + 3, y + 0, z + 15, Blocks.air, 0, 3);
//		world.setBlock(x + 4, y + 0, z + 15, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 15, Blocks.air, 0, 3);
//		world.setBlock(x + 6, y + 0, z + 15, Blocks.air, 0, 3);
//		world.setBlock(x + 7, y + 0, z + 15, Blocks.air, 0, 3);
//		world.setBlock(x + 8, y + 0, z + 15, Blocks.air, 0, 3);
//		world.setBlock(x + 9, y + 0, z + 15, Blocks.air, 0, 3);
//		world.setBlock(x + 10, y + 0, z + 15, Blocks.air, 0, 3);
//		world.setBlock(x + 11, y + 0, z + 15, Blocks.air, 0, 3);
//		world.setBlock(x + 12, y + 0, z + 15, Blocks.air, 0, 3);
//		world.setBlock(x + 13, y + 0, z + 15, Blocks.air, 0, 3);
//		world.setBlock(x + 14, y + 0, z + 15, Blocks.air, 0, 3);
//		world.setBlock(x + 15, y + 0, z + 15, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 15, Blocks.air, 0, 3);
//		world.setBlock(x + 17, y + 0, z + 15, Blocks.air, 0, 3);
//		world.setBlock(x + 18, y + 0, z + 15, Blocks.air, 0, 3);
		world.setBlock(x + 19, y + 0, z + 15, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 20, y + 0, z + 15, Blocks.air, 0, 3);
//		world.setBlock(x + 0, y + 0, z + 16, Blocks.air, 0, 3);
		world.setBlock(x + 1, y + 0, z + 16, Blocks.sandstone, 2, 3);
		world.setBlock(x + 2, y + 0, z + 16, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 3, y + 0, z + 16, Blocks.air, 0, 3);
//		world.setBlock(x + 4, y + 0, z + 16, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 16, Blocks.air, 0, 3);
//		world.setBlock(x + 6, y + 0, z + 16, Blocks.air, 0, 3);
//		world.setBlock(x + 7, y + 0, z + 16, Blocks.air, 0, 3);
//		world.setBlock(x + 8, y + 0, z + 16, Blocks.air, 0, 3);
//		world.setBlock(x + 9, y + 0, z + 16, Blocks.air, 0, 3);
//		world.setBlock(x + 10, y + 0, z + 16, Blocks.air, 0, 3);
//		world.setBlock(x + 11, y + 0, z + 16, Blocks.air, 0, 3);
//		world.setBlock(x + 12, y + 0, z + 16, Blocks.air, 0, 3);
//		world.setBlock(x + 13, y + 0, z + 16, Blocks.air, 0, 3);
//		world.setBlock(x + 14, y + 0, z + 16, Blocks.air, 0, 3);
//		world.setBlock(x + 15, y + 0, z + 16, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 16, Blocks.air, 0, 3);
//		world.setBlock(x + 17, y + 0, z + 16, Blocks.air, 0, 3);
		world.setBlock(x + 18, y + 0, z + 16, Blocks.sandstone, 2, 3);
		world.setBlock(x + 19, y + 0, z + 16, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 20, y + 0, z + 16, Blocks.air, 0, 3);
//		world.setBlock(x + 0, y + 0, z + 17, Blocks.air, 0, 3);
//		world.setBlock(x + 1, y + 0, z + 17, Blocks.air, 0, 3);
		world.setBlock(x + 2, y + 0, z + 17, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 3, y + 0, z + 17, Blocks.air, 0, 3);
//		world.setBlock(x + 4, y + 0, z + 17, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 17, Blocks.air, 0, 3);
//		world.setBlock(x + 6, y + 0, z + 17, Blocks.air, 0, 3);
//		world.setBlock(x + 7, y + 0, z + 17, Blocks.air, 0, 3);
//		world.setBlock(x + 8, y + 0, z + 17, Blocks.air, 0, 3);
//		world.setBlock(x + 9, y + 0, z + 17, Blocks.air, 0, 3);
//		world.setBlock(x + 10, y + 0, z + 17, Blocks.air, 0, 3);
//		world.setBlock(x + 11, y + 0, z + 17, Blocks.air, 0, 3);
//		world.setBlock(x + 12, y + 0, z + 17, Blocks.air, 0, 3);
//		world.setBlock(x + 13, y + 0, z + 17, Blocks.air, 0, 3);
//		world.setBlock(x + 14, y + 0, z + 17, Blocks.air, 0, 3);
//		world.setBlock(x + 15, y + 0, z + 17, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 17, Blocks.air, 0, 3);
//		world.setBlock(x + 17, y + 0, z + 17, Blocks.air, 0, 3);
		world.setBlock(x + 18, y + 0, z + 17, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 19, y + 0, z + 17, Blocks.air, 0, 3);
//		world.setBlock(x + 20, y + 0, z + 17, Blocks.air, 0, 3);
//		world.setBlock(x + 0, y + 0, z + 18, Blocks.air, 0, 3);
//		world.setBlock(x + 1, y + 0, z + 18, Blocks.air, 0, 3);
		world.setBlock(x + 2, y + 0, z + 18, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 3, y + 0, z + 18, Blocks.air, 0, 3);
//		world.setBlock(x + 4, y + 0, z + 18, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 18, Blocks.air, 0, 3);
//		world.setBlock(x + 6, y + 0, z + 18, Blocks.air, 0, 3);
//		world.setBlock(x + 7, y + 0, z + 18, Blocks.air, 0, 3);
//		world.setBlock(x + 8, y + 0, z + 18, Blocks.air, 0, 3);
//		world.setBlock(x + 9, y + 0, z + 18, Blocks.air, 0, 3);
//		world.setBlock(x + 10, y + 0, z + 18, Blocks.air, 0, 3);
//		world.setBlock(x + 11, y + 0, z + 18, Blocks.air, 0, 3);
//		world.setBlock(x + 12, y + 0, z + 18, Blocks.air, 0, 3);
//		world.setBlock(x + 13, y + 0, z + 18, Blocks.air, 0, 3);
//		world.setBlock(x + 14, y + 0, z + 18, Blocks.air, 0, 3);
//		world.setBlock(x + 15, y + 0, z + 18, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 18, Blocks.air, 0, 3);
//		world.setBlock(x + 17, y + 0, z + 18, Blocks.air, 0, 3);
		world.setBlock(x + 18, y + 0, z + 18, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 19, y + 0, z + 18, Blocks.air, 0, 3);
//		world.setBlock(x + 20, y + 0, z + 18, Blocks.air, 0, 3);
//		world.setBlock(x + 0, y + 0, z + 19, Blocks.air, 0, 3);
//		world.setBlock(x + 1, y + 0, z + 19, Blocks.air, 0, 3);
		world.setBlock(x + 2, y + 0, z + 19, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 3, y + 0, z + 19, Blocks.air, 0, 3);
//		world.setBlock(x + 4, y + 0, z + 19, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 19, Blocks.air, 0, 3);
//		world.setBlock(x + 6, y + 0, z + 19, Blocks.air, 0, 3);
//		world.setBlock(x + 7, y + 0, z + 19, Blocks.air, 0, 3);
//		world.setBlock(x + 8, y + 0, z + 19, Blocks.air, 0, 3);
//		world.setBlock(x + 9, y + 0, z + 19, Blocks.air, 0, 3);
//		world.setBlock(x + 10, y + 0, z + 19, Blocks.air, 0, 3);
//		world.setBlock(x + 11, y + 0, z + 19, Blocks.air, 0, 3);
//		world.setBlock(x + 12, y + 0, z + 19, Blocks.air, 0, 3);
//		world.setBlock(x + 13, y + 0, z + 19, Blocks.air, 0, 3);
//		world.setBlock(x + 14, y + 0, z + 19, Blocks.air, 0, 3);
//		world.setBlock(x + 15, y + 0, z + 19, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 19, Blocks.air, 0, 3);
//		world.setBlock(x + 17, y + 0, z + 19, Blocks.air, 0, 3);
		world.setBlock(x + 18, y + 0, z + 19, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 19, y + 0, z + 19, Blocks.air, 0, 3);
//		world.setBlock(x + 20, y + 0, z + 19, Blocks.air, 0, 3);
//		world.setBlock(x + 0, y + 0, z + 20, Blocks.air, 0, 3);
//		world.setBlock(x + 1, y + 0, z + 20, Blocks.air, 0, 3);
		world.setBlock(x + 2, y + 0, z + 20, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 3, y + 0, z + 20, Blocks.air, 0, 3);
//		world.setBlock(x + 4, y + 0, z + 20, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 20, Blocks.air, 0, 3);
//		world.setBlock(x + 6, y + 0, z + 20, Blocks.air, 0, 3);
//		world.setBlock(x + 7, y + 0, z + 20, Blocks.air, 0, 3);
//		world.setBlock(x + 8, y + 0, z + 20, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 0, z + 20, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 0, z + 20, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 0, z + 20, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 12, y + 0, z + 20, Blocks.air, 0, 3);
//		world.setBlock(x + 13, y + 0, z + 20, Blocks.air, 0, 3);
//		world.setBlock(x + 14, y + 0, z + 20, Blocks.air, 0, 3);
//		world.setBlock(x + 15, y + 0, z + 20, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 20, Blocks.air, 0, 3);
//		world.setBlock(x + 17, y + 0, z + 20, Blocks.air, 0, 3);
		world.setBlock(x + 18, y + 0, z + 20, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 19, y + 0, z + 20, Blocks.air, 0, 3);
//		world.setBlock(x + 20, y + 0, z + 20, Blocks.air, 0, 3);
//		world.setBlock(x + 0, y + 0, z + 21, Blocks.air, 0, 3);
//		world.setBlock(x + 1, y + 0, z + 21, Blocks.air, 0, 3);
		world.setBlock(x + 2, y + 0, z + 21, Blocks.sandstone, 2, 3);
		world.setBlock(x + 3, y + 0, z + 21, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 4, y + 0, z + 21, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 21, Blocks.air, 0, 3);
//		world.setBlock(x + 6, y + 0, z + 21, Blocks.air, 0, 3);
//		world.setBlock(x + 7, y + 0, z + 21, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 0, z + 21, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 9, y + 0, z + 21, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 0, z + 21, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 0, z + 21, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 0, z + 21, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 13, y + 0, z + 21, Blocks.air, 0, 3);
		world.setBlock(x + 14, y + 0, z + 21, Blocks.air, 0, 3);
		world.setBlock(x + 15, y + 0, z + 21, Blocks.air, 0, 3);
		world.setBlock(x + 16, y + 0, z + 21, Blocks.air, 0, 3);
		world.setBlock(x + 17, y + 0, z + 21, Blocks.sandstone, 2, 3);
		world.setBlock(x + 18, y + 0, z + 21, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 19, y + 0, z + 21, Blocks.air, 0, 3);
//		world.setBlock(x + 20, y + 0, z + 21, Blocks.air, 0, 3);
//		world.setBlock(x + 0, y + 0, z + 22, Blocks.air, 0, 3);
//		world.setBlock(x + 1, y + 0, z + 22, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 22, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 0, z + 22, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 4, y + 0, z + 22, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 22, Blocks.air, 0, 3);
//		world.setBlock(x + 6, y + 0, z + 22, Blocks.air, 0, 3);
//		world.setBlock(x + 7, y + 0, z + 22, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 0, z + 22, Blocks.stonebrick, 1, 3);
		world.setBlock(x + 9, y + 0, z + 22, Blocks.stone_brick_stairs, 3, 3);
		world.setBlock(x + 10, y + 0, z + 22, Blocks.stone_brick_stairs, 3, 3);
		world.setBlock(x + 11, y + 0, z + 22, Blocks.stone_brick_stairs, 3, 3);
		world.setBlock(x + 12, y + 0, z + 22, Blocks.stonebrick, 2, 3);
//		world.setBlock(x + 13, y + 0, z + 22, Blocks.air, 0, 3);
//		world.setBlock(x + 14, y + 0, z + 22, Blocks.air, 0, 3);
//		world.setBlock(x + 15, y + 0, z + 22, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 22, Blocks.air, 0, 3);
		world.setBlock(x + 17, y + 0, z + 22, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 18, y + 0, z + 22, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 22, Blocks.air, 0, 3);
//		world.setBlock(x + 20, y + 0, z + 22, Blocks.air, 0, 3);
//		world.setBlock(x + 0, y + 0, z + 23, Blocks.air, 0, 3);
//		world.setBlock(x + 1, y + 0, z + 23, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 23, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 0, z + 23, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 4, y + 0, z + 23, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 23, Blocks.air, 0, 3);
//		world.setBlock(x + 6, y + 0, z + 23, Blocks.air, 0, 3);
//		world.setBlock(x + 7, y + 0, z + 23, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 0, z + 23, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 9, y + 0, z + 23, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 0, z + 23, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 0, z + 23, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 0, z + 23, Blocks.stonebrick, 1, 3);
//		world.setBlock(x + 13, y + 0, z + 23, Blocks.air, 0, 3);
//		world.setBlock(x + 14, y + 0, z + 23, Blocks.air, 0, 3);
//		world.setBlock(x + 15, y + 0, z + 23, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 23, Blocks.air, 0, 3);
		world.setBlock(x + 17, y + 0, z + 23, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 18, y + 0, z + 23, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 23, Blocks.air, 0, 3);
//		world.setBlock(x + 20, y + 0, z + 23, Blocks.air, 0, 3);
//		world.setBlock(x + 0, y + 0, z + 24, Blocks.air, 0, 3);
//		world.setBlock(x + 1, y + 0, z + 24, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 24, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 0, z + 24, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 4, y + 0, z + 24, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 24, Blocks.air, 0, 3);
//		world.setBlock(x + 6, y + 0, z + 24, Blocks.air, 0, 3);
//		world.setBlock(x + 7, y + 0, z + 24, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 0, z + 24, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 9, y + 0, z + 24, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 0, z + 24, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 0, z + 24, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 0, z + 24, Blocks.stonebrick, 0, 3);
//		world.setBlock(x + 13, y + 0, z + 24, Blocks.air, 0, 3);
//		world.setBlock(x + 14, y + 0, z + 24, Blocks.air, 0, 3);
//		world.setBlock(x + 15, y + 0, z + 24, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 24, Blocks.air, 0, 3);
		world.setBlock(x + 17, y + 0, z + 24, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 18, y + 0, z + 24, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 24, Blocks.air, 0, 3);
//		world.setBlock(x + 20, y + 0, z + 24, Blocks.air, 0, 3);
//		world.setBlock(x + 0, y + 0, z + 25, Blocks.air, 0, 3);
//		world.setBlock(x + 1, y + 0, z + 25, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 25, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 0, z + 25, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 0, z + 25, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 5, y + 0, z + 25, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 6, y + 0, z + 25, Blocks.stonebrick, 2, 3);
		world.setBlock(x + 7, y + 0, z + 25, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 8, y + 0, z + 25, Blocks.stonebrick, 2, 3);
		world.setBlock(x + 9, y + 0, z + 25, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 0, z + 25, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 0, z + 25, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 0, z + 25, Blocks.stonebrick, 1, 3);
		world.setBlock(x + 13, y + 0, z + 25, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 14, y + 0, z + 25, Blocks.stonebrick, 2, 3);
		world.setBlock(x + 15, y + 0, z + 25, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 16, y + 0, z + 25, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 17, y + 0, z + 25, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 18, y + 0, z + 25, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 25, Blocks.air, 0, 3);
//		world.setBlock(x + 20, y + 0, z + 25, Blocks.air, 0, 3);
//		world.setBlock(x + 0, y + 0, z + 26, Blocks.air, 0, 3);
//		world.setBlock(x + 1, y + 0, z + 26, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 26, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 0, z + 26, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 0, z + 26, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 5, y + 0, z + 26, Blocks.web, 0, 3);
		world.setBlock(x + 7, y + 0, z + 26, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 0, z + 26, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 0, z + 26, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 0, z + 26, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 0, z + 26, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 0, z + 26, Blocks.air, 0, 3);
		world.setBlock(x + 13, y + 0, z + 26, Blocks.air, 0, 3);
		world.setBlock(x + 15, y + 0, z + 26, Blocks.web, 0, 3);
		world.setBlock(x + 16, y + 0, z + 26, Blocks.stonebrick, 2, 3);
		world.setBlock(x + 17, y + 0, z + 26, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 18, y + 0, z + 26, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 26, Blocks.air, 0, 3);
//		world.setBlock(x + 20, y + 0, z + 26, Blocks.air, 0, 3);
//		world.setBlock(x + 0, y + 0, z + 27, Blocks.air, 0, 3);
//		world.setBlock(x + 1, y + 0, z + 27, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 27, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 0, z + 27, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 0, z + 27, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 5, y + 0, z + 27, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 0, z + 27, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 0, z + 27, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 0, z + 27, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 0, z + 27, Blocks.air, 0, 3);

		preventLag();

		world.setBlock(x + 10, y + 0, z + 27, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 0, z + 27, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 0, z + 27, Blocks.air, 0, 3);
		world.setBlock(x + 13, y + 0, z + 27, Blocks.air, 0, 3);
		world.setBlock(x + 14, y + 0, z + 27, Blocks.air, 0, 3);
		world.setBlock(x + 15, y + 0, z + 27, Blocks.air, 0, 3);
		world.setBlock(x + 16, y + 0, z + 27, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 17, y + 0, z + 27, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 18, y + 0, z + 27, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 27, Blocks.air, 0, 3);
//		world.setBlock(x + 20, y + 0, z + 27, Blocks.air, 0, 3);
//		world.setBlock(x + 0, y + 0, z + 28, Blocks.air, 0, 3);
//		world.setBlock(x + 1, y + 0, z + 28, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 28, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 0, z + 28, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 0, z + 28, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 5, y + 0, z + 28, Blocks.web, 0, 3);
		world.setBlock(x + 6, y + 0, z + 28, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 0, z + 28, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 0, z + 28, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 0, z + 28, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 0, z + 28, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 0, z + 28, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 0, z + 28, Blocks.air, 0, 3);
		world.setBlock(x + 13, y + 0, z + 28, Blocks.air, 0, 3);
		world.setBlock(x + 14, y + 0, z + 28, Blocks.air, 0, 3);
		world.setBlock(x + 15, y + 0, z + 28, Blocks.web, 0, 3);
		world.setBlock(x + 16, y + 0, z + 28, Blocks.stonebrick, 1, 3);
		world.setBlock(x + 17, y + 0, z + 28, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 18, y + 0, z + 28, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 28, Blocks.air, 0, 3);
//		world.setBlock(x + 20, y + 0, z + 28, Blocks.air, 0, 3);
//		world.setBlock(x + 0, y + 0, z + 29, Blocks.air, 0, 3);
//		world.setBlock(x + 1, y + 0, z + 29, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 29, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 0, z + 29, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 0, z + 29, Blocks.stonebrick, 2, 3);
		world.setBlock(x + 5, y + 0, z + 29, Blocks.web, 0, 3);
		world.setBlock(x + 6, y + 0, z + 29, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 0, z + 29, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 0, z + 29, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 0, z + 29, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 0, z + 29, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 0, z + 29, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 0, z + 29, Blocks.air, 0, 3);
		world.setBlock(x + 13, y + 0, z + 29, Blocks.air, 0, 3);
		world.setBlock(x + 14, y + 0, z + 29, Blocks.air, 0, 3);
		world.setBlock(x + 15, y + 0, z + 29, Blocks.air, 0, 3);
		world.setBlock(x + 16, y + 0, z + 29, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 17, y + 0, z + 29, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 18, y + 0, z + 29, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 29, Blocks.air, 0, 3);
//		world.setBlock(x + 20, y + 0, z + 29, Blocks.air, 0, 3);
//		world.setBlock(x + 0, y + 0, z + 30, Blocks.air, 0, 3);
//		world.setBlock(x + 1, y + 0, z + 30, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 30, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 0, z + 30, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 0, z + 30, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 5, y + 0, z + 30, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 0, z + 30, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 0, z + 30, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 0, z + 30, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 0, z + 30, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 0, z + 30, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 0, z + 30, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 0, z + 30, Blocks.air, 0, 3);
		world.setBlock(x + 13, y + 0, z + 30, Blocks.air, 0, 3);
		world.setBlock(x + 14, y + 0, z + 30, Blocks.air, 0, 3);
		world.setBlock(x + 15, y + 0, z + 30, Blocks.air, 0, 3);
		world.setBlock(x + 16, y + 0, z + 30, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 17, y + 0, z + 30, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 18, y + 0, z + 30, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 30, Blocks.air, 0, 3);
//		world.setBlock(x + 20, y + 0, z + 30, Blocks.air, 0, 3);
//		world.setBlock(x + 0, y + 0, z + 31, Blocks.air, 0, 3);
//		world.setBlock(x + 1, y + 0, z + 31, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 31, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 0, z + 31, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 0, z + 31, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 0, z + 31, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 0, z + 31, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 0, z + 31, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 0, z + 31, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 0, z + 31, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 0, z + 31, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 0, z + 31, Blocks.air, 0, 3);
		world.setBlock(x + 13, y + 0, z + 31, Blocks.air, 0, 3);
		world.setBlock(x + 14, y + 0, z + 31, Blocks.air, 0, 3);
		world.setBlock(x + 16, y + 0, z + 31, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 0, z + 31, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 18, y + 0, z + 31, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 31, Blocks.air, 0, 3);
//		world.setBlock(x + 20, y + 0, z + 31, Blocks.air, 0, 3);
//		world.setBlock(x + 0, y + 0, z + 32, Blocks.air, 0, 3);
//		world.setBlock(x + 1, y + 0, z + 32, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 32, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 0, z + 32, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 0, z + 32, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 0, z + 32, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 0, z + 32, Blocks.web, 0, 3);
		world.setBlock(x + 8, y + 0, z + 32, Blocks.web, 0, 3);
		world.setBlock(x + 9, y + 0, z + 32, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 0, z + 32, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 0, z + 32, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 0, z + 32, Blocks.air, 0, 3);
		world.setBlock(x + 13, y + 0, z + 32, Blocks.air, 0, 3);
		world.setBlock(x + 15, y + 0, z + 32, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 0, z + 32, Blocks.sandstone, 2, 3);
		world.setBlock(x + 17, y + 0, z + 32, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 18, y + 0, z + 32, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 32, Blocks.air, 0, 3);
//		world.setBlock(x + 20, y + 0, z + 32, Blocks.air, 0, 3);
//		world.setBlock(x + 0, y + 0, z + 33, Blocks.air, 0, 3);
//		world.setBlock(x + 1, y + 0, z + 33, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 33, Blocks.air, 0, 3);
//		world.setBlock(x + 3, y + 0, z + 33, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 0, z + 33, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 0, z + 33, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 0, z + 33, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 0, z + 33, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 8, y + 0, z + 33, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 9, y + 0, z + 33, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 10, y + 0, z + 33, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 11, y + 0, z + 33, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 12, y + 0, z + 33, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 13, y + 0, z + 33, Blocks.stonebrick, 2, 3);
		world.setBlock(x + 14, y + 0, z + 33, Blocks.sandstone, 2, 3);
		world.setBlock(x + 15, y + 0, z + 33, Blocks.sandstone, 2, 3);
		world.setBlock(x + 16, y + 0, z + 33, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 17, y + 0, z + 33, Blocks.air, 0, 3);
//		world.setBlock(x + 18, y + 0, z + 33, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 33, Blocks.air, 0, 3);
//		world.setBlock(x + 20, y + 0, z + 33, Blocks.air, 0, 3);
//		world.setBlock(x + 0, y + 0, z + 34, Blocks.air, 0, 3);
//		world.setBlock(x + 1, y + 0, z + 34, Blocks.air, 0, 3);
//		world.setBlock(x + 2, y + 0, z + 34, Blocks.air, 0, 3);
//		world.setBlock(x + 3, y + 0, z + 34, Blocks.air, 0, 3);
//		world.setBlock(x + 4, y + 0, z + 34, Blocks.air, 0, 3);
//		world.setBlock(x + 5, y + 0, z + 34, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 0, z + 34, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 0, z + 34, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 0, z + 34, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 0, z + 34, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 0, z + 34, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 0, z + 34, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 0, z + 34, Blocks.sandstone, 2, 3);
		world.setBlock(x + 13, y + 0, z + 34, Blocks.sandstone, 2, 3);
		world.setBlock(x + 14, y + 0, z + 34, Blocks.sandstone, 2, 3);
//		world.setBlock(x + 15, y + 0, z + 34, Blocks.air, 0, 3);
//		world.setBlock(x + 16, y + 0, z + 34, Blocks.air, 0, 3);
//		world.setBlock(x + 17, y + 0, z + 34, Blocks.air, 0, 3);
//		world.setBlock(x + 18, y + 0, z + 34, Blocks.air, 0, 3);
//		world.setBlock(x + 19, y + 0, z + 34, Blocks.air, 0, 3);
//		world.setBlock(x + 20, y + 0, z + 34, Blocks.air, 0, 3);

		// Stairs down, from SphinxStairs.schematic
		// 5 wide (x) x 4 length (z) x 3 height (y)
		new SphinxStairs().generate_r00(world, random, x + 8, y - 3, z + 21);

		// Lower Room, from SphinxLowerRoom.schematic
		// 13 wide (x) x 9 length (z) x 3 height (y)
		new SphinxLowerRoom().generate_r00(world, random, x + 4, y - 3, z + 25);

		//adding a chest with random stuff
		// If just one chest, set last two parameters to 1 and false (or here, where we want them both)
		int numChests = 1;
		boolean generatedChest = false;
		// Upper floor (1 double chest)
		generateDoubleChest(world, random, x + 15, y + 2, z + 3, x + 16, y + 2, z + 3,  4, numChests, generatedChest);	
//		world.setBlock(x + 15, y + 2, z + 3, Blocks.chest, 3, 3);
//		world.setBlock(x + 16, y + 2, z + 3, Blocks.chest, 3, 3);

		// Lower floor (2 double chests)
		generateDoubleChest(world, random, x + 4 + 1, y - 3 + 2, z + 25 + 1, x + 4 + 1, y - 1, z + 25 + 2, 5, numChests, generatedChest);	
		generateDoubleChest(world, random, x + 4 + 11, y - 3 + 2, z + 25 + 1, x + 4 + 11, y - 1, z + 25 + 2, 4, numChests, generatedChest);	
//		world.setBlock(x + 1, y + 2, z + 1, Blocks.chest, 5, 3);
//		world.setBlock(x + 1, y + 2, z + 2, Blocks.chest, 5, 3);
//		world.setBlock(x + 11, y + 2, z + 1, Blocks.chest, 4, 3);
//		world.setBlock(x + 11, y + 2, z + 2, Blocks.chest, 4, 3);
		
		// Mob spawners upper level (by stairs?)
		generateMobSpawner(world, random, x + 8, y + 1, z + 21, 0);		
		generateMobSpawner(world, random, x + 12, y + 1, z + 21, 0);		
		generateMobSpawner(world, random, x + 7, y + 2, z + 4, 0);		
		generateMobSpawner(world, random, x + 13, y + 2, z + 4, 0);		
//		world.setBlock(x + 8, y + 1, z + 21, Blocks.mob_spawner, 0, 3);
//		world.setBlock(x + 12, y + 1, z + 21, Blocks.mob_spawner, 0, 3);
//		world.setBlock(x + 7, y + 2, z + 4, Blocks.mob_spawner, 0, 3);
//		world.setBlock(x + 13, y + 2, z + 4, Blocks.mob_spawner, 0, 3);

		// Mob spawner lower room
		generateMobSpawner(world, random, x + 4 + 1, y - 3 + 1, z + 25 + 1, 0);		
		generateMobSpawner(world, random, x + 4 + 11, y - 3 + 1, z + 25 + 1, 0);		
//		world.setBlock(x + 1, y + 1, z + 1, Blocks.mob_spawner, 0, 3);
//		world.setBlock(x + 11, y + 1, z + 1, Blocks.mob_spawner, 0, 3);

		running = false; // All built, let another thread start now
		
		return true;
	}
}
