package com.thexfactor117.ascension.structures;

import java.util.Random;

import com.thexfactor117.ascension.help.LogHelper;

import net.minecraft.init.Blocks;
import net.minecraft.world.World;

/**
 * 
 * @author WILLIAM
 *
 */
public class SphinxLowerRoom extends Sphinx_000 {

	public void generate_r00(World world, Random random, int x, int y, int z) {
		LogHelper.info("Generating lower room for Sphinx at " + x + "," + y + "," + z + "!");

		world.setBlock(x + 0, y + 2, z + 0, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 1, y + 2, z + 0, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 2, y + 2, z + 0, Blocks.stonebrick, 1, 3);
		world.setBlock(x + 3, y + 2, z + 0, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 4, y + 2, z + 0, Blocks.stonebrick, 1, 3);
		world.setBlock(x + 5, y + 2, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 2, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 2, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 2, z + 0, Blocks.stonebrick, 2, 3);
		world.setBlock(x + 9, y + 2, z + 0, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 10, y + 2, z + 0, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 11, y + 2, z + 0, Blocks.stonebrick, 1, 3);
		world.setBlock(x + 12, y + 2, z + 0, Blocks.stonebrick, 1, 3);
		world.setBlock(x + 0, y + 2, z + 1, Blocks.stonebrick, 1, 3);
//		world.setBlock(x + 1, y + 2, z + 1, Blocks.chest, 5, 3);
		world.setBlock(x + 2, y + 2, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 2, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 2, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 2, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 2, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 2, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 2, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 2, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 2, z + 1, Blocks.web, 0, 3);
//		world.setBlock(x + 11, y + 2, z + 1, Blocks.chest, 4, 3);
		world.setBlock(x + 12, y + 2, z + 1, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 0, y + 2, z + 2, Blocks.stonebrick, 2, 3);
//		world.setBlock(x + 1, y + 2, z + 2, Blocks.chest, 5, 3);
		world.setBlock(x + 2, y + 2, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 2, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 2, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 2, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 2, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 2, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 2, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 2, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 2, z + 2, Blocks.air, 0, 3);
//		world.setBlock(x + 11, y + 2, z + 2, Blocks.chest, 4, 3);
		world.setBlock(x + 12, y + 2, z + 2, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 0, y + 2, z + 3, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 1, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 2, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 2, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 2, z + 3, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 0, y + 2, z + 4, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 1, y + 2, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 2, y + 2, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 2, z + 4, Blocks.air, 0, 3);

		preventLag();

		world.setBlock(x + 4, y + 2, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 2, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 2, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 2, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 2, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 2, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 2, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 2, z + 4, Blocks.web, 0, 3);
		world.setBlock(x + 12, y + 2, z + 4, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 0, y + 2, z + 5, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 1, y + 2, z + 5, Blocks.web, 0, 3);
		world.setBlock(x + 2, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 2, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 2, z + 5, Blocks.stonebrick, 1, 3);
		world.setBlock(x + 0, y + 2, z + 6, Blocks.stonebrick, 1, 3);
		world.setBlock(x + 1, y + 2, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 2, y + 2, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 2, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 2, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 2, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 2, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 2, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 2, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 2, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 2, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 2, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 2, z + 6, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 0, y + 2, z + 7, Blocks.stonebrick, 2, 3);
		world.setBlock(x + 1, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 2, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 2, z + 7, Blocks.web, 0, 3);
		world.setBlock(x + 6, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 2, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 2, z + 7, Blocks.web, 0, 3);
		world.setBlock(x + 12, y + 2, z + 7, Blocks.stonebrick, 2, 3);
		world.setBlock(x + 0, y + 2, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 1, y + 2, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 2, y + 2, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 3, y + 2, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 4, y + 2, z + 8, Blocks.stonebrick, 2, 3);
		world.setBlock(x + 5, y + 2, z + 8, Blocks.stonebrick, 1, 3);
		world.setBlock(x + 6, y + 2, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 7, y + 2, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 8, y + 2, z + 8, Blocks.stonebrick, 2, 3);
		world.setBlock(x + 9, y + 2, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 10, y + 2, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 11, y + 2, z + 8, Blocks.stonebrick, 1, 3);
		world.setBlock(x + 12, y + 2, z + 8, Blocks.stonebrick, 0, 3);

		world.setBlock(x + 0, y + 1, z + 0, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 1, y + 1, z + 0, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 2, y + 1, z + 0, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 3, y + 1, z + 0, Blocks.stonebrick, 2, 3);
		world.setBlock(x + 4, y + 1, z + 0, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 5, y + 1, z + 0, Blocks.air, 0, 3);

		preventLag();

		world.setBlock(x + 6, y + 1, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 1, z + 0, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 1, z + 0, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 9, y + 1, z + 0, Blocks.stonebrick, 1, 3);
		world.setBlock(x + 10, y + 1, z + 0, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 11, y + 1, z + 0, Blocks.stonebrick, 2, 3);
		world.setBlock(x + 12, y + 1, z + 0, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 0, y + 1, z + 1, Blocks.stonebrick, 0, 3);
//		world.setBlock(x + 1, y + 1, z + 1, Blocks.mob_spawner, 0, 3);
		world.setBlock(x + 2, y + 1, z + 1, Blocks.stone_brick_stairs, 1, 3);
		world.setBlock(x + 3, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 1, z + 1, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 1, z + 1, Blocks.stone_brick_stairs, 0, 3);
//		world.setBlock(x + 11, y + 1, z + 1, Blocks.mob_spawner, 0, 3);
		world.setBlock(x + 12, y + 1, z + 1, Blocks.stonebrick, 2, 3);
		world.setBlock(x + 0, y + 1, z + 2, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 1, y + 1, z + 2, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 2, y + 1, z + 2, Blocks.stone_brick_stairs, 1, 3);
		world.setBlock(x + 3, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 1, z + 2, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 1, z + 2, Blocks.stone_brick_stairs, 0, 3);
		world.setBlock(x + 11, y + 1, z + 2, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 12, y + 1, z + 2, Blocks.stonebrick, 1, 3);
		world.setBlock(x + 0, y + 1, z + 3, Blocks.stonebrick, 1, 3);
		world.setBlock(x + 1, y + 1, z + 3, Blocks.stone_brick_stairs, 3, 3);
		world.setBlock(x + 2, y + 1, z + 3, Blocks.web, 0, 3);
		world.setBlock(x + 3, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 1, z + 3, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 1, z + 3, Blocks.stone_brick_stairs, 3, 3);
		world.setBlock(x + 12, y + 1, z + 3, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 0, y + 1, z + 4, Blocks.stonebrick, 1, 3);
		world.setBlock(x + 1, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 2, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 1, z + 4, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 1, z + 4, Blocks.stonebrick, 2, 3);
		world.setBlock(x + 0, y + 1, z + 5, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 1, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 2, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 1, z + 5, Blocks.air, 0, 3);
		world.setBlock(x + 12, y + 1, z + 5, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 0, y + 1, z + 6, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 1, y + 1, z + 6, Blocks.web, 0, 3);
		world.setBlock(x + 2, y + 1, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 1, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 1, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 5, y + 1, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 1, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 1, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 8, y + 1, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 9, y + 1, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 1, z + 6, Blocks.air, 0, 3);
		world.setBlock(x + 11, y + 1, z + 6, Blocks.web, 0, 3);
		world.setBlock(x + 12, y + 1, z + 6, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 0, y + 1, z + 7, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 1, y + 1, z + 7, Blocks.web, 0, 3);
		world.setBlock(x + 2, y + 1, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 3, y + 1, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 4, y + 1, z + 7, Blocks.web, 0, 3);
		world.setBlock(x + 5, y + 1, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 6, y + 1, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 7, y + 1, z + 7, Blocks.web, 0, 3);
		world.setBlock(x + 8, y + 1, z + 7, Blocks.web, 0, 3);
		world.setBlock(x + 9, y + 1, z + 7, Blocks.air, 0, 3);
		world.setBlock(x + 10, y + 1, z + 7, Blocks.web, 0, 3);
		world.setBlock(x + 11, y + 1, z + 7, Blocks.web, 0, 3);
		world.setBlock(x + 12, y + 1, z + 7, Blocks.stonebrick, 2, 3);
		world.setBlock(x + 0, y + 1, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 1, y + 1, z + 8, Blocks.stonebrick, 1, 3);
		world.setBlock(x + 2, y + 1, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 3, y + 1, z + 8, Blocks.stonebrick, 2, 3);
		world.setBlock(x + 4, y + 1, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 5, y + 1, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 6, y + 1, z + 8, Blocks.stonebrick, 1, 3);
		world.setBlock(x + 7, y + 1, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 8, y + 1, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 9, y + 1, z + 8, Blocks.stonebrick, 2, 3);
		world.setBlock(x + 10, y + 1, z + 8, Blocks.stonebrick, 1, 3);
		world.setBlock(x + 11, y + 1, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 12, y + 1, z + 8, Blocks.stonebrick, 0, 3);

		world.setBlock(x + 0, y + 0, z + 0, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 1, y + 0, z + 0, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 2, y + 0, z + 0, Blocks.stonebrick, 1, 3);
		world.setBlock(x + 3, y + 0, z + 0, Blocks.stonebrick, 0, 3);

		preventLag();

		world.setBlock(x + 4, y + 0, z + 0, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 5, y + 0, z + 0, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 0, z + 0, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 0, z + 0, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 0, z + 0, Blocks.stonebrick, 1, 3);
		world.setBlock(x + 9, y + 0, z + 0, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 10, y + 0, z + 0, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 11, y + 0, z + 0, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 12, y + 0, z + 0, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 0, y + 0, z + 1, Blocks.stonebrick, 2, 3);
		world.setBlock(x + 1, y + 0, z + 1, Blocks.sandstone, 2, 3);
		world.setBlock(x + 2, y + 0, z + 1, Blocks.sandstone, 2, 3);
		world.setBlock(x + 3, y + 0, z + 1, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 0, z + 1, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 0, z + 1, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 0, z + 1, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 0, z + 1, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 0, z + 1, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 0, z + 1, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 0, z + 1, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 0, z + 1, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 0, z + 1, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 0, y + 0, z + 2, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 1, y + 0, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 2, y + 0, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 3, y + 0, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 0, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 0, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 0, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 0, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 0, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 0, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 0, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 0, z + 2, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 0, z + 2, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 0, y + 0, z + 3, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 1, y + 0, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 2, y + 0, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 3, y + 0, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 0, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 0, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 0, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 0, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 0, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 0, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 0, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 0, z + 3, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 0, z + 3, Blocks.stonebrick, 2, 3);
		world.setBlock(x + 0, y + 0, z + 4, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 1, y + 0, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 2, y + 0, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 3, y + 0, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 0, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 0, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 0, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 0, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 0, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 0, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 0, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 0, z + 4, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 0, z + 4, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 0, y + 0, z + 5, Blocks.stonebrick, 1, 3);
		world.setBlock(x + 1, y + 0, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 2, y + 0, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 3, y + 0, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 0, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 0, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 0, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 0, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 0, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 0, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 0, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 0, z + 5, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 0, z + 5, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 0, y + 0, z + 6, Blocks.stonebrick, 2, 3);
		world.setBlock(x + 1, y + 0, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 2, y + 0, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 3, y + 0, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 0, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 0, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 0, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 0, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 0, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 0, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 0, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 0, z + 6, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 0, z + 6, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 0, y + 0, z + 7, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 1, y + 0, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 2, y + 0, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 3, y + 0, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 4, y + 0, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 5, y + 0, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 6, y + 0, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 7, y + 0, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 8, y + 0, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 9, y + 0, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 10, y + 0, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 11, y + 0, z + 7, Blocks.sandstone, 2, 3);
		world.setBlock(x + 12, y + 0, z + 7, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 0, y + 0, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 1, y + 0, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 2, y + 0, z + 8, Blocks.stonebrick, 2, 3);
		world.setBlock(x + 3, y + 0, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 4, y + 0, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 5, y + 0, z + 8, Blocks.stonebrick, 1, 3);
		world.setBlock(x + 6, y + 0, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 7, y + 0, z + 8, Blocks.stonebrick, 2, 3);
		world.setBlock(x + 8, y + 0, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 9, y + 0, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 10, y + 0, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 11, y + 0, z + 8, Blocks.stonebrick, 0, 3);
		world.setBlock(x + 12, y + 0, z + 8, Blocks.stonebrick, 0, 3);
	}
}
